"use client";

import { useMemo, useState, useTransition } from "react";
import { addDays, addMonths, endOfMonth, endOfWeek, format, isSameMonth, parseISO, startOfMonth, startOfWeek, subMonths } from "date-fns";
import { CalendarDays, ChevronLeft, ChevronRight, Filter, Search, Users } from "lucide-react";
import { toast } from "sonner";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { LeaveStatusBadge } from "@/components/leave/leave-status-badge";
import { loadLeaveCalendarMonth, reviewLeaveRequest } from "@/lib/leave/actions";
import type { LeaveCalendarEvent, LeaveCalendarMonth } from "@/lib/leave/definitions";

const initials=(name:string)=>name.split(" ").map((part)=>part[0]).join("").slice(0,2).toUpperCase();
const todayKey=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date());
const eventTone:Record<string,string>={EL:"border-violet-200 bg-violet-50 text-violet-800",SL:"border-cyan-200 bg-cyan-50 text-cyan-800",RH:"border-amber-200 bg-amber-50 text-amber-800"};

export function AdminLeaveCalendar({initial,canReview}:{initial:LeaveCalendarMonth;canReview:boolean}){
  const [data,setData]=useState(initial);const [month,setMonth]=useState(parseISO(`${initial.month}-01`));const [loading,startTransition]=useTransition();const [search,setSearch]=useState("");const [showFilters,setShowFilters]=useState(false);const [status,setStatus]=useState("Approved");const [leaveType,setLeaveType]=useState("all");const [department,setDepartment]=useState("all");const [location,setLocation]=useState("all");const [selectedEvent,setSelectedEvent]=useState<LeaveCalendarEvent|null>(null);const [selectedDate,setSelectedDate]=useState<string|null>(null);
  const changeMonth=(next:Date)=>startTransition(async()=>{const key=format(next,"yyyy-MM");try{const result=await loadLeaveCalendarMonth(key);setData(result);setMonth(next);setSelectedDate(null)}catch(error){toast.error(error instanceof Error?error.message:"Calendar could not be loaded.")}});
  const events=useMemo(()=>data.events.filter((event)=>(status==="all"||event.status===status)&&(leaveType==="all"||event.leaveCode===leaveType)&&(department==="all"||event.department===department)&&(location==="all"||event.location===location)),[data.events,status,leaveType,department,location]);
  const searchKey=search.trim().toLowerCase();const monthStart=startOfMonth(month);const gridStart=startOfWeek(monthStart,{weekStartsOn:1});const gridEnd=endOfWeek(endOfMonth(month),{weekStartsOn:1});const dates=[];for(let date=gridStart;date<=gridEnd;date=addDays(date,1))dates.push(date);const today=todayKey();
  const eventsFor=(key:string)=>events.filter((event)=>event.dates.includes(key));const selectedEvents=selectedDate?eventsFor(selectedDate):[];const approved=events.filter((event)=>event.status==="Approved");const pendingCount=data.events.filter((event)=>event.status.startsWith("Pending")||event.status==="Submitted").length;const todayCount=new Set(data.events.filter((event)=>event.status==="Approved"&&event.dates.includes(today)).map((event)=>event.employeeId)).size;const upcoming=data.events.filter((event)=>event.status==="Approved"&&event.fromDate>today).length;
  const decide=(decision:"approved"|"rejected")=>{if(!selectedEvent)return;startTransition(async()=>{const result=await reviewLeaveRequest(selectedEvent.id,decision);if(!result.ok){toast.error(result.message);return}toast.success(result.message);setSelectedEvent(null);const refreshed=await loadLeaveCalendarMonth(data.month);setData(refreshed)})};
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-semibold">Leave Calendar</h3><p className="text-sm text-muted-foreground">Approved workforce absence by date</p></div><div className="flex flex-wrap items-center gap-2"><Button variant="outline" size="sm" onClick={()=>changeMonth(parseISO(`${today.slice(0,7)}-01`))}>Today</Button><div className="flex"><Button variant="outline" size="icon-sm" className="rounded-r-none" onClick={()=>changeMonth(subMonths(month,1))} aria-label="Previous month"><ChevronLeft/></Button><Button variant="outline" size="icon-sm" className="rounded-l-none border-l-0" onClick={()=>changeMonth(addMonths(month,1))} aria-label="Next month"><ChevronRight/></Button></div><input type="month" value={format(month,"yyyy-MM")} onChange={(event)=>changeMonth(parseISO(`${event.target.value}-01`))} className="h-8 rounded-md border bg-background px-2 text-sm"/><Badge variant="outline">Month</Badge></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Employees on leave today",todayCount],["Approved leaves this month",approved.length],["Pending requests",pendingCount],["Upcoming leaves",upcoming]].map(([label,value])=><Card key={String(label)}><CardContent className="flex items-center justify-between p-4"><div><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div><CalendarDays className="size-5 text-primary"/></CardContent></Card>)}</div>
    <div className="flex flex-wrap gap-2"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search employee" className="pl-9"/></div><Button variant="outline" onClick={()=>setShowFilters((value)=>!value)}><Filter/>Filters{[status!=="Approved",leaveType!=="all",department!=="all",location!=="all"].filter(Boolean).length>0&&<Badge>{[status!=="Approved",leaveType!=="all",department!=="all",location!=="all"].filter(Boolean).length}</Badge>}</Button></div>
    {showFilters&&<div className="grid gap-3 rounded-xl border bg-muted/20 p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-medium">Status<select value={status} onChange={(event)=>setStatus(event.target.value)} className="mt-1 h-9 w-full rounded-md border bg-background px-2 text-sm"><option>Approved</option><option>Pending Manager</option><option>Pending Hr</option><option>Submitted</option><option>Rejected</option><option value="all">All statuses</option></select></label><label className="text-xs font-medium">Leave type<select value={leaveType} onChange={(event)=>setLeaveType(event.target.value)} className="mt-1 h-9 w-full rounded-md border bg-background px-2 text-sm"><option value="all">All types</option><option value="EL">Earned Leave</option><option value="SL">Sick Leave</option><option value="RH">Restricted Holiday</option></select></label><label className="text-xs font-medium">Department<select value={department} onChange={(event)=>setDepartment(event.target.value)} className="mt-1 h-9 w-full rounded-md border bg-background px-2 text-sm"><option value="all">All departments</option>{data.departments.map((item)=><option key={item}>{item}</option>)}</select></label><label className="text-xs font-medium">Location<select value={location} onChange={(event)=>setLocation(event.target.value)} className="mt-1 h-9 w-full rounded-md border bg-background px-2 text-sm"><option value="all">All locations</option>{data.locations.map((item)=><option key={item}>{item}</option>)}</select></label><div className="sm:col-span-2 lg:col-span-4 flex justify-end"><Button variant="ghost" size="sm" onClick={()=>{setStatus("Approved");setLeaveType("all");setDepartment("all");setLocation("all")}}>Clear all</Button></div></div>}
    <div className={`overflow-hidden rounded-xl border bg-background ${loading?"opacity-60":""}`} aria-busy={loading}><div className="grid grid-cols-7 border-b bg-muted/30">{["MON","TUE","WED","THU","FRI","SAT","SUN"].map((day,index)=><div key={day} className={`px-2 py-2 text-center text-[11px] font-semibold tracking-wide text-muted-foreground ${index>4?"bg-muted/50":""}`}>{day}</div>)}</div><div className="hidden grid-cols-7 md:grid">{dates.map((date)=>{const key=format(date,"yyyy-MM-dd");const dayEvents=eventsFor(key);const holiday=data.holidays.find((item)=>item.date===key);return <button type="button" key={key} onClick={()=>setSelectedDate(key)} className={`min-h-32 border-b border-r p-1.5 text-left align-top hover:bg-accent/30 ${!isSameMonth(date,month)?"bg-muted/20 text-muted-foreground":date.getDay()===0||date.getDay()===6?"bg-muted/30":""} ${selectedDate===key?"ring-2 ring-inset ring-primary":""}`}><div className="mb-1 flex items-center justify-between"><span className={`flex size-6 items-center justify-center rounded-full text-xs ${key===today?"bg-primary font-semibold text-primary-foreground":""}`}>{format(date,"d")}</span>{holiday&&<span className="max-w-20 truncate text-[9px] font-medium text-rose-600" title={holiday.name}>{holiday.name}</span>}</div><div className="space-y-1">{dayEvents.slice(0,3).map((event)=>{const matched=!searchKey||`${event.employeeName} ${event.employeeCode}`.toLowerCase().includes(searchKey);return <span role="button" tabIndex={0} key={event.id} onClick={(click)=>{click.stopPropagation();setSelectedEvent(event)}} onKeyDown={(press)=>{if(press.key==="Enter"){press.stopPropagation();setSelectedEvent(event)}}} className={`flex items-center gap-1 truncate rounded border px-1 py-0.5 text-[10px] ${eventTone[event.leaveCode]} ${event.status!=="Approved"?"border-dashed opacity-75":""} ${searchKey&&!matched?"opacity-25":matched&&searchKey?"ring-1 ring-primary":""}`}><Avatar className="size-4"><AvatarFallback className="text-[7px]">{initials(event.employeeName)}</AvatarFallback></Avatar><span className="truncate">{event.employeeName}</span><b className="ml-auto">{event.leaveCode}</b></span>})}{dayEvents.length>3&&<span role="button" className="block px-1 text-[10px] font-semibold text-primary">+{dayEvents.length-3} more</span>}</div></button>})}</div>
      <div className="grid grid-cols-7 md:hidden">{dates.map((date)=>{const key=format(date,"yyyy-MM-dd");const count=eventsFor(key).length;return <button key={key} onClick={()=>setSelectedDate(key)} className={`min-h-14 border-b border-r p-1 text-center text-xs ${!isSameMonth(date,month)?"text-muted-foreground opacity-40":""} ${selectedDate===key?"bg-accent ring-1 ring-inset ring-primary":""}`}><span className={`mx-auto flex size-6 items-center justify-center rounded-full ${key===today?"bg-primary text-primary-foreground":""}`}>{format(date,"d")}</span>{count>0&&<span className="mx-auto mt-1 block size-1.5 rounded-full bg-primary" aria-label={`${count} leave entries`}/>}</button>})}</div></div>
    {selectedDate&&<Card className="md:hidden"><CardContent className="p-4"><p className="font-semibold">{format(parseISO(selectedDate),"MMMM d, yyyy")}</p><p className="mt-1 text-xs text-muted-foreground">On leave: {selectedEvents.filter((event)=>event.status==="Approved").length} · Pending: {selectedEvents.filter((event)=>event.status.startsWith("Pending")||event.status==="Submitted").length} · Working: {Math.max(0,data.employeeCount-new Set(selectedEvents.filter((event)=>event.status==="Approved").map((event)=>event.employeeId)).size)}</p><div className="mt-3 space-y-2">{selectedEvents.map((event)=><button key={event.id} onClick={()=>setSelectedEvent(event)} className="flex w-full items-center gap-2 rounded-lg border p-2 text-left"><Avatar className="size-7"><AvatarFallback>{initials(event.employeeName)}</AvatarFallback></Avatar><span className="flex-1 text-sm">{event.employeeName}</span><LeaveStatusBadge status={event.status}/></button>)}</div></CardContent></Card>}
    <Dialog open={Boolean(selectedDate)} onOpenChange={(open)=>{if(!open)setSelectedDate(null)}}><DialogContent><DialogHeader><DialogTitle>{selectedDate?format(parseISO(selectedDate),"MMMM d, yyyy"):"Date details"}</DialogTitle><DialogDescription>Daily workforce availability overview</DialogDescription></DialogHeader>{selectedDate&&<div><div className="grid grid-cols-3 gap-3">{[["On leave",selectedEvents.filter((event)=>event.status==="Approved").length],["Pending",selectedEvents.filter((event)=>event.status.startsWith("Pending")||event.status==="Submitted").length],["Working",Math.max(0,data.employeeCount-new Set(selectedEvents.filter((event)=>event.status==="Approved").map((event)=>event.employeeId)).size)]].map(([label,value])=><div key={String(label)} className="rounded-lg bg-muted p-3 text-center"><p className="text-xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>)}</div><div className="mt-4 max-h-72 space-y-2 overflow-y-auto">{selectedEvents.map((event)=><button key={event.id} onClick={()=>{setSelectedDate(null);setSelectedEvent(event)}} className="grid w-full grid-cols-[1fr_auto] rounded-lg border p-3 text-left"><span><b className="text-sm">{event.employeeName}</b><span className="block text-xs text-muted-foreground">{event.department} · {event.leaveName}</span></span><LeaveStatusBadge status={event.status}/></button>)}{selectedEvents.length===0&&<p className="py-8 text-center text-sm text-muted-foreground">No leave entries for this date.</p>}</div></div>}</DialogContent></Dialog>
    <Dialog open={Boolean(selectedEvent)} onOpenChange={(open)=>{if(!open)setSelectedEvent(null)}}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Leave details</DialogTitle><DialogDescription>Request and employee information</DialogDescription></DialogHeader>{selectedEvent&&<div className="space-y-4"><div className="flex items-center gap-3"><Avatar className="size-12"><AvatarFallback>{initials(selectedEvent.employeeName)}</AvatarFallback></Avatar><div><p className="font-semibold">{selectedEvent.employeeName}</p><p className="text-sm text-muted-foreground">{selectedEvent.employeeCode} · {selectedEvent.department} · {selectedEvent.designation}</p></div></div><div className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2">{[["Leave type",selectedEvent.leaveName],["Dates",`${format(parseISO(selectedEvent.fromDate),"dd MMM yyyy")} – ${format(parseISO(selectedEvent.toDate),"dd MMM yyyy")}`],["Duration",`${selectedEvent.quantity} days · ${selectedEvent.session.replaceAll("_"," ")}`],["Status",selectedEvent.status],["Requested",new Date(selectedEvent.requestedAt).toLocaleString("en-IN")],["Approved by",selectedEvent.approvedBy]].map(([label,value])=><div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="text-sm font-medium capitalize">{value}</p></div>)}<div className="sm:col-span-2"><p className="text-xs text-muted-foreground">Reason</p><p className="text-sm">{selectedEvent.reason}</p></div></div>{canReview&&(selectedEvent.status.startsWith("Pending")||selectedEvent.status==="Submitted")&&<div className="flex justify-end gap-2"><Button variant="outline" disabled={loading} onClick={()=>decide("rejected")}><ChevronLeft/>Reject</Button><Button disabled={loading} onClick={()=>decide("approved")}><Users/>Approve</Button></div>}</div>}</DialogContent></Dialog>
  </div>;
}
