"use client";
/* eslint-disable react-hooks/incompatible-library -- TanStack Table v8 exposes non-memoizable callbacks by design. */

import { useActionState, useMemo, useState, useTransition } from "react";
import Link from "next/link";
import { DndProvider, useDrag, useDrop } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";
import { createColumnHelper, flexRender, getCoreRowModel, getFilteredRowModel, useReactTable } from "@tanstack/react-table";
import { Activity, Building2, ChevronDown, ChevronRight, Download, GitBranch, Layers3, MapPin, Maximize2, Network, Plus, Search, ShieldCheck, Sparkles, Trash2, Users } from "lucide-react";
import { toast } from "sonner";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createDesignation, createOrganisationNode, deleteDesignation, deleteOrganisationNode, mapEmployee, moveOrganisationNode } from "./actions";

type OrgNode = { id: string; company_id: string; parent_id: string | null; node_type: string; name: string; code: string; description: string | null; head_user_id: string | null; status: string; sort_order: number };
type Designation = { id: string; name: string; code: string | null; level: number; parent_id: string | null; status: string };
type Employee = { id: string; full_name: string; email: string; employee_code: string | null; employment_status: string; organisation_node_id: string | null; designation_id: string | null; reporting_manager_id: string | null; secondary_manager_id: string | null; cost_centre: string | null; grade: string | null; employee_level: string | null };
type Log = { id: string; entity_type: string; action: string; changes: unknown; created_at: string; actor_user_id: string | null };
type HierarchyNode = { employee: Employee; children: HierarchyNode[] };
type Props = { company: { id: string; name: string }; nodes: OrgNode[]; designations: Designation[]; employees: Employee[]; logs: Log[]; canManage: boolean; canDelete: boolean; initialTab: OrganisationTab };

const kinds: Record<string, { label: string; icon: typeof Building2; color: string }> = {
  company: { label: "Company", icon: Building2, color: "bg-violet-100 text-violet-700" }, business_unit: { label: "Business unit", icon: Layers3, color: "bg-blue-100 text-blue-700" }, location: { label: "Location", icon: MapPin, color: "bg-emerald-100 text-emerald-700" }, department: { label: "Department", icon: Network, color: "bg-amber-100 text-amber-700" }, sub_department: { label: "Sub department", icon: GitBranch, color: "bg-orange-100 text-orange-700" }, team: { label: "Team", icon: Users, color: "bg-rose-100 text-rose-700" },
};

const organisationTabs = [
  ["dashboard", "Dashboard"],
  ["tree", "Organisation Tree"],
  ["designations", "Designations"],
  ["chart", "Org Chart"],
  ["mapping", "Employee Mapping"],
  ["logs", "Activity Logs"],
] as const;

export type OrganisationTab = (typeof organisationTabs)[number][0];

export function OrganisationWorkspace(props: Props) {
  const tab = props.initialTab;
  const activeEmployees = props.employees.filter((item) => item.employment_status === "active");
  const heads = new Set(props.nodes.map((item) => item.head_user_id).filter(Boolean));
  const kpis = [
    ["Organisation", props.company.name, Building2, "tree"], ["Business Units", count("business_unit"), Layers3, "tree"], ["Locations", count("location"), MapPin, "tree"], ["Departments", count("department") + count("sub_department"), Network, "tree"], ["Teams", count("team"), Users, "tree"], ["Active Employees", activeEmployees.length, ShieldCheck, "mapping"], ["Department Heads", heads.size, GitBranch, "chart"], ["Vacant Positions", Math.max(0, props.designations.length - new Set(props.employees.map((e) => e.designation_id).filter(Boolean)).size), Sparkles, "designations"],
  ] as const;
  function count(kind: string) { return props.nodes.filter((item) => item.node_type === kind && item.status === "active").length; }
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">{props.company.name}</p><h2 className="mt-1 text-2xl font-bold tracking-tight">Organisation Management</h2><p className="mt-1 text-sm text-muted-foreground">Build structures, reporting lines, designations, and employee assignments for your organisation.</p></div><Badge variant="outline" className="w-fit border-emerald-200 bg-emerald-50 text-emerald-700">Single organisation</Badge></div>
    <div className="space-y-5">
      <div className="sticky top-0 z-20 -mx-1 overflow-x-auto bg-background/95 px-1 py-2 backdrop-blur">
        <div role="tablist" aria-label="Organisation sections" className="flex min-w-max items-center gap-1">
          {organisationTabs.map(([value, label]) => (
            <Link
              key={value}
              id={`organisation-tab-${value}`}
              href={value === "dashboard" ? "/admin/organization" : `/admin/organization?tab=${value}`}
              role="tab"
              aria-selected={tab === value}
              aria-controls={`organisation-panel-${value}`}
              className={`relative h-8 rounded-md border border-transparent px-2 py-1 text-sm font-medium whitespace-nowrap transition-colors after:absolute after:inset-x-0 after:-bottom-1 after:h-0.5 after:bg-foreground after:transition-opacity hover:text-foreground focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 focus-visible:outline-none ${tab === value ? "text-foreground after:opacity-100" : "text-foreground/60 after:opacity-0"}`}
            >
              {label}
            </Link>
          ))}
        </div>
      </div>
      <div id={`organisation-panel-${tab}`} role="tabpanel" aria-labelledby={`organisation-tab-${tab}`}>
        {tab === "dashboard" && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(([label, value, Icon, target]) => <Link href={`/admin/organization?tab=${target}`} key={label} className="text-left"><Card className="h-full border-border/80 shadow-none transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><CardContent className="p-5"><div className="flex items-center justify-between gap-3"><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><Icon className="h-5 w-5" /></span><span className="truncate text-right text-2xl font-bold">{value}</span></div><p className="mt-4 font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">View records →</p></CardContent></Card></Link>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[1.3fr_1fr]"><ChartPreview {...props} /><Card className="shadow-none"><CardHeader><CardTitle className="text-base">Structure health</CardTitle></CardHeader><CardContent className="space-y-4">{[["Employees mapped", props.employees.filter(e=>e.organisation_node_id).length, props.employees.length],["Managers assigned", props.employees.filter(e=>e.reporting_manager_id).length, props.employees.length],["Nodes with heads", heads.size, Math.max(1, props.nodes.length)]].map(([label,value,total]) => <div key={String(label)}><div className="mb-1.5 flex justify-between text-xs"><span>{label}</span><span>{value}/{total}</span></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{ width: `${Math.round(Number(value)/Math.max(1,Number(total))*100)}%` }} /></div></div>)}</CardContent></Card></div></>}
        {tab === "tree" && <DndProvider backend={HTML5Backend}><OrganisationTree {...props} /></DndProvider>}
        {tab === "designations" && <DesignationTable {...props} />}
        {tab === "chart" && <OrgChart {...props} />}
        {tab === "mapping" && <EmployeeMapping {...props} />}
        {tab === "logs" && <ActivityLogs logs={props.logs} employees={props.employees} />}
      </div>
    </div>
  </div>;
}

function OrganisationTree(props: Props) {
  const [query, setQuery] = useState(""); const [expanded, setExpanded] = useState<Set<string>>(new Set(props.nodes.map(n=>n.id)));
  const roots = props.nodes.filter(n=>!n.parent_id); const matches = (n: OrgNode) => !query || `${n.name} ${n.code} ${n.node_type}`.toLowerCase().includes(query.toLowerCase());
  return <Card className="min-h-[560px] shadow-none"><CardHeader className="sticky top-12 z-10 border-b bg-background"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><CardTitle>Organisation Tree</CardTitle><p className="mt-1 text-sm text-muted-foreground">Drag nodes onto a new parent to preview hierarchy changes.</p></div><div className="flex flex-wrap gap-2"><div className="relative"><Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search nodes…" className="w-52 pl-8"/></div><Button variant="outline" onClick={()=>setExpanded(new Set(props.nodes.map(n=>n.id)))}>Expand all</Button><Button variant="outline" onClick={()=>setExpanded(new Set())}>Collapse all</Button>{props.canManage && <NodeDialog nodes={props.nodes} employees={props.employees}/>}</div></div></CardHeader><CardContent className="grid gap-5 p-5 lg:grid-cols-[1fr_300px]"><div className="rounded-xl border bg-muted/20 p-3">{roots.length ? roots.map(node=><TreeNode key={node.id} node={node} nodes={props.nodes} employees={props.employees} expanded={expanded} setExpanded={setExpanded} matches={matches} canDelete={props.canDelete}/>) : <Empty title="No organisation structure yet" description="Create your company root and add business units, locations, departments, and teams."/>}</div><div className="rounded-xl border p-4"><h3 className="font-semibold">Hierarchy guide</h3><p className="mt-1 text-xs text-muted-foreground">Recommended enterprise structure</p><div className="mt-4 space-y-2">{Object.entries(kinds).map(([key,item])=><div key={key} className="flex items-center gap-2 text-sm"><span className={`rounded-lg p-1.5 ${item.color}`}><item.icon className="h-3.5 w-3.5"/></span>{item.label}</div>)}</div></div></CardContent></Card>;
}

function TreeNode({node,nodes,employees,expanded,setExpanded,matches,canDelete}:{node:OrgNode;nodes:OrgNode[];employees:Employee[];expanded:Set<string>;setExpanded:(v:Set<string>)=>void;matches:(n:OrgNode)=>boolean;canDelete:boolean}) {
  const children=nodes.filter(n=>n.parent_id===node.id); const [{isDragging},drag]=useDrag(()=>({type:"ORG_NODE",item:{id:node.id},collect:m=>({isDragging:m.isDragging()})}),[node.id]); const [{isOver},drop]=useDrop(()=>({accept:"ORG_NODE",drop:async(item:{id:string})=>{if(item.id===node.id)return;const source=nodes.find(n=>n.id===item.id);if(!window.confirm(`Move ${source?.name??"this node"} under ${node.name}?`))return;const result=await moveOrganisationNode(item.id,node.id);if(result.ok)toast.success("Organisation node moved");else toast.error("Node could not be moved",{description:"Check hierarchy rules and try again."});},collect:m=>({isOver:m.isOver()})}),[node.id,node.name,nodes]);
  if(!matches(node)&&!children.some(matches)) return null; const meta=kinds[node.node_type]??kinds.department; const head=employees.find(e=>e.id===node.head_user_id);
  return <div className="ml-2"><div ref={el=>{drag(drop(el));}} className={`my-1 flex items-center gap-2 rounded-lg border bg-background p-2.5 transition ${isDragging?"opacity-40":""} ${isOver?"border-primary bg-primary/5":"border-transparent"}`}><button onClick={()=>{const next=new Set(expanded);if(next.has(node.id)) next.delete(node.id); else next.add(node.id);setExpanded(next)}} className="p-1">{children.length?(expanded.has(node.id)?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>):<span className="block h-4 w-4"/>}</button><span className={`rounded-lg p-2 ${meta.color}`}><meta.icon className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{node.name}</p><p className="text-xs text-muted-foreground">{node.code} · {meta.label}{head?` · ${head.full_name}`:""}</p></div><Badge variant="outline">{employees.filter(e=>e.organisation_node_id===node.id).length}</Badge>{canDelete&&<DeleteOrganisationNodeButton node={node}/>}</div>{expanded.has(node.id)&&children.length>0&&<div className="ml-5 border-l pl-2">{children.map(child=><TreeNode key={child.id} node={child} nodes={nodes} employees={employees} expanded={expanded} setExpanded={setExpanded} matches={matches} canDelete={canDelete}/>)}</div>}</div>;
}

function DeleteOrganisationNodeButton({node}:{node:OrgNode}){const[pending,startTransition]=useTransition();return <Button type="button" variant="ghost" size="icon-sm" disabled={pending} title={`Delete ${node.name}`} className="text-muted-foreground hover:bg-destructive/10 hover:text-destructive" onClick={()=>{if(!window.confirm(`Delete ${node.name}? This cannot be undone.`))return;startTransition(async()=>{const result=await deleteOrganisationNode(node.id);if(result.ok)toast.success(result.message);else toast.error("Organisation node not deleted",{description:result.message});});}}><Trash2/><span className="sr-only">Delete {node.name}</span></Button>}

function NodeDialog({nodes,employees}:{nodes:OrgNode[];employees:Employee[]}) { return <Dialog><DialogTrigger render={<Button/>}><Plus/>Add node</DialogTrigger><DialogContent className="sm:max-w-lg"><form action={createOrganisationNode} onSubmit={()=>toast.success("Organisation node submitted")}><DialogHeader><DialogTitle>Add organisation node</DialogTitle><DialogDescription>Codes must be unique within this organisation.</DialogDescription></DialogHeader><div className="grid gap-4 py-4 sm:grid-cols-2"><Field label="Name" name="name" required/><Field label="Unique code" name="code" placeholder="ENG_CORE" required/><SelectField label="Type" name="nodeType" options={Object.entries(kinds).filter(([value])=>value!=="company").map(([value,m])=>({value,label:m.label}))}/><SelectField label="Parent" name="parentId" options={nodes.map(n=>({value:n.id,label:n.name}))} empty="Organisation root"/><SelectField label="Department head" name="headUserId" options={employees.filter(e=>e.employment_status==="active").map(e=>({value:e.id,label:e.full_name}))} empty="Unassigned"/><Field label="Description" name="description"/></div><DialogFooter><Button type="submit">Create node</Button></DialogFooter></form></DialogContent></Dialog>; }

const designationColumn=createColumnHelper<Designation>();
function DesignationTable(props:Props){const [filter,setFilter]=useState("");const columns=useMemo(()=>[designationColumn.accessor("name",{header:"Designation",cell:i=><span className="font-semibold">{i.getValue()}</span>}),designationColumn.accessor("code",{header:"Code",cell:i=><span className="font-mono text-xs">{i.getValue()??"—"}</span>}),designationColumn.accessor("level",{header:"Level",cell:i=>`L${i.getValue()}`}),designationColumn.accessor("parent_id",{header:"Reports to",cell:i=>props.designations.find(d=>d.id===i.getValue())?.name??"Top level"}),designationColumn.accessor("status",{header:"Status",cell:i=><Badge variant="outline">{i.getValue()}</Badge>}),...(props.canDelete?[designationColumn.display({id:"actions",header:"",cell:i=><div className="flex justify-end"><DeleteDesignationButton designation={i.row.original}/></div>})]:[])],[props.designations,props.canDelete]);const table=useReactTable({data:props.designations,columns,state:{globalFilter:filter},onGlobalFilterChange:setFilter,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel()});return <Card className="shadow-none"><CardHeader><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><CardTitle>Designation Management</CardTitle><p className="mt-1 text-sm text-muted-foreground">Define titles, levels, and designation hierarchy.</p></div><div className="flex gap-2"><Input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Search designations…"/>{props.canManage&&<DesignationDialog designations={props.designations}/>}</div></div></CardHeader><CardContent><div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-muted/50">{table.getHeaderGroups().map(g=><tr key={g.id}>{g.headers.map(h=><th key={h.id} className="px-4 py-3 text-xs uppercase text-muted-foreground">{flexRender(h.column.columnDef.header,h.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row=><tr key={row.id} className="border-t hover:bg-muted/20">{row.getVisibleCells().map(cell=><td key={cell.id} className="px-4 py-3">{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table>{!table.getRowModel().rows.length&&<Empty title="No designations" description="Add the first designation to establish career levels."/>}</div></CardContent></Card>}
function DeleteDesignationButton({designation}:{designation:Designation}){const[pending,startTransition]=useTransition();return <Button type="button" variant="ghost" size="icon-sm" disabled={pending} title={`Delete ${designation.name}`} className="text-muted-foreground hover:bg-destructive/10 hover:text-destructive" onClick={()=>{if(!window.confirm(`Delete ${designation.name}? This cannot be undone.`))return;startTransition(async()=>{const result=await deleteDesignation(designation.id);if(result.ok)toast.success(result.message);else toast.error("Designation not deleted",{description:result.message});});}}><Trash2/><span className="sr-only">Delete {designation.name}</span></Button>}
function DesignationDialog({designations}:{designations:Designation[]}){const[open,setOpen]=useState(false);const[state,action,pending]=useActionState(createDesignation,undefined);return <Dialog open={open} onOpenChange={setOpen}><Button type="button" onClick={()=>setOpen(true)} aria-haspopup="dialog" aria-expanded={open}><Plus/>Add</Button><DialogContent><form action={action}><DialogHeader><DialogTitle>Create designation</DialogTitle><DialogDescription>Add a unique title and its hierarchy level.</DialogDescription></DialogHeader><div className="space-y-4 py-4"><Field label="Designation name" name="name" required minLength={2}/><Field label="Code" name="code" placeholder="SWE-2" required minLength={2} maxLength={20} pattern="[A-Za-z0-9_-]+"/><Field label="Level (1–20)" name="level" type="number" defaultValue="1" min={1} max={20} required/><SelectField label="Parent designation" name="parentId" options={designations.map(d=>({value:d.id,label:d.name}))} empty="Top level"/></div>{state&&<p role="status" className={`pb-3 text-sm ${state.ok?"text-emerald-600":"text-destructive"}`}>{state.message}</p>}<DialogFooter><Button type="submit" disabled={pending}>{pending?"Creating…":"Create designation"}</Button></DialogFooter></form></DialogContent></Dialog>}

function OrgChart(props:Props){const forest=useMemo(()=>buildOrganisationForest(props.employees),[props.employees]);return <Card className="overflow-hidden shadow-none"><CardHeader className="border-b"><div className="flex justify-between gap-4"><div><CardTitle>Organisation Chart</CardTitle><p className="mt-1 text-sm text-muted-foreground">Manager-to-employee reporting hierarchy for all {props.employees.length} employee records.</p></div><Button variant="outline" onClick={()=>window.print()}><Download/>Export</Button></div></CardHeader><CardContent className="min-h-[560px] overflow-auto bg-[radial-gradient(circle,var(--border)_1px,transparent_1px)] bg-[size:24px_24px] p-10">{forest.length?<div className="mx-auto flex min-w-max items-start justify-center gap-12">{forest.map(node=><HierarchyBranch key={node.employee.id} node={node} employees={props.employees} designations={props.designations}/>)}</div>:<Empty title="No employees found" description="Create an employee record to generate the organisation chart."/>}</CardContent></Card>}
function HierarchyBranch({node,employees,designations}:{node:HierarchyNode;employees:Employee[];designations:Designation[]}){const employee=node.employee;const manager=employees.find(item=>item.id===employee.reporting_manager_id);const designation=designations.find(item=>item.id===employee.designation_id)?.name??employee.employee_code??"Employee";return <div className="flex flex-col items-center"><div className="w-64 rounded-xl border bg-background p-4 text-left shadow-sm"><div className="flex items-center gap-3"><Avatar className="h-10 w-10"><AvatarFallback>{initials(employee.full_name)}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="truncate font-semibold">{employee.full_name}</p><p className="truncate text-xs text-muted-foreground">{designation}</p></div><Badge variant="outline" className="capitalize">{employee.employment_status}</Badge></div><div className="mt-3 flex items-center justify-between gap-3 border-t pt-2 text-xs text-muted-foreground"><span>{manager?<>Reports to <strong className="font-medium text-foreground">{manager.full_name}</strong></>:"Top level"}</span><span>{node.children.length} direct report{node.children.length===1?"":"s"}</span></div></div>{node.children.length>0&&<><div className="h-6 w-px bg-border"/><div className="relative flex items-start gap-6 border-t border-border pt-6">{node.children.map(child=><div key={child.employee.id} className="relative before:absolute before:-top-6 before:left-1/2 before:h-6 before:w-px before:bg-border"><HierarchyBranch node={child} employees={employees} designations={designations}/></div>)}</div></>}</div>}
function buildOrganisationForest(employees:Employee[]){const nodes=new Map<string,HierarchyNode>(employees.map(employee=>[employee.id,{employee,children:[]}]));const roots:HierarchyNode[]=[];const createsCycle=(employee:Employee,managerId:string)=>{const visited=new Set([employee.id]);let currentId:string|null=managerId;while(currentId){if(visited.has(currentId))return true;visited.add(currentId);currentId=nodes.get(currentId)?.employee.reporting_manager_id??null}return false};nodes.forEach(node=>{const managerId=node.employee.reporting_manager_id;const manager=managerId?nodes.get(managerId):undefined;if(!manager||managerId===node.employee.id||createsCycle(node.employee,managerId!))roots.push(node);else manager.children.push(node)});const sortNodes=(items:HierarchyNode[])=>{items.sort((a,b)=>a.employee.full_name.localeCompare(b.employee.full_name));items.forEach(item=>sortNodes(item.children))};sortNodes(roots);return roots}
function ChartPreview(props:Props){return <Card className="shadow-none"><CardHeader><div className="flex justify-between"><CardTitle className="text-base">Reporting snapshot</CardTitle><Maximize2 className="h-4 w-4 text-muted-foreground"/></div></CardHeader><CardContent><div className="flex flex-wrap justify-center gap-3">{props.employees.filter(e=>!e.reporting_manager_id).slice(0,4).map(e=><div key={e.id} className="rounded-xl border p-3 text-center"><Avatar className="mx-auto"><AvatarFallback>{initials(e.full_name)}</AvatarFallback></Avatar><p className="mt-2 text-sm font-semibold">{e.full_name}</p><p className="text-xs text-muted-foreground">{props.employees.filter(x=>x.reporting_manager_id===e.id).length} direct reports</p></div>)}</div>{!props.employees.length&&<Empty title="No employees" description="Add employees to generate the reporting chart."/>}</CardContent></Card>}

function EmployeeMapping(props:Props){const [query,setQuery]=useState("");const rows=props.employees.filter(e=>`${e.full_name} ${e.employee_code} ${e.email}`.toLowerCase().includes(query.toLowerCase()));return <Card className="shadow-none"><CardHeader><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><CardTitle>Employee Mapping</CardTitle><p className="mt-1 text-sm text-muted-foreground">Assign organisation, designation, managers, cost centre, grade, and level.</p></div><div className="flex gap-2"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employees…"/><Button variant="outline" onClick={()=>toast.info("Bulk assignment",{description:"Select employees after importing a mapping CSV."})}><Download/>Bulk assign</Button></div></div></CardHeader><CardContent><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-muted/50"><tr>{["Employee","Organisation","Designation","Manager","Grade / Level","Action"].map(h=><th key={h} className="px-4 py-3 text-xs uppercase text-muted-foreground">{h}</th>)}</tr></thead><tbody>{rows.map(e=><tr key={e.id} className="border-t"><td className="px-4 py-3"><p className="font-semibold">{e.full_name}</p><p className="text-xs text-muted-foreground">{e.employee_code??e.email}</p></td><td className="px-4 py-3">{props.nodes.find(n=>n.id===e.organisation_node_id)?.name??<span className="text-amber-600">Unmapped</span>}</td><td className="px-4 py-3">{props.designations.find(d=>d.id===e.designation_id)?.name??"—"}</td><td className="px-4 py-3">{props.employees.find(m=>m.id===e.reporting_manager_id)?.full_name??"—"}</td><td className="px-4 py-3">{[e.grade,e.employee_level].filter(Boolean).join(" · ")||"—"}</td><td className="px-4 py-3">{props.canManage&&<MappingDialog employee={e} {...props}/>}</td></tr>)}</tbody></table></div></CardContent></Card>}
function MappingDialog({employee,...props}:Props&{employee:Employee}){return <Dialog><DialogTrigger render={<Button variant="outline" size="sm"/>}>Map</DialogTrigger><DialogContent className="sm:max-w-xl"><form action={mapEmployee} onSubmit={()=>toast.success("Employee mapping submitted")}><input type="hidden" name="employeeId" value={employee.id}/><DialogHeader><DialogTitle>Map {employee.full_name}</DialogTitle><DialogDescription>Reporting-loop validation is also enforced by the data layer.</DialogDescription></DialogHeader><div className="grid gap-4 py-4 sm:grid-cols-2"><SelectField label="Organisation node" name="nodeId" defaultValue={employee.organisation_node_id??""} options={props.nodes.map(n=>({value:n.id,label:n.name}))}/><SelectField label="Designation" name="designationId" defaultValue={employee.designation_id??""} options={props.designations.map(d=>({value:d.id,label:d.name}))}/><SelectField label="Reporting manager" name="managerId" defaultValue={employee.reporting_manager_id??""} options={props.employees.filter(e=>e.id!==employee.id&&e.employment_status==="active").map(e=>({value:e.id,label:e.full_name}))} empty="Unassigned"/><SelectField label="Secondary manager" name="secondaryManagerId" defaultValue={employee.secondary_manager_id??""} options={props.employees.filter(e=>e.id!==employee.id&&e.employment_status==="active").map(e=>({value:e.id,label:e.full_name}))} empty="Unassigned"/><Field label="Cost centre" name="costCentre" defaultValue={employee.cost_centre??""}/><Field label="Grade" name="grade" defaultValue={employee.grade??""}/><Field label="Level" name="level" defaultValue={employee.employee_level??""}/></div><DialogFooter><Button type="submit">Save mapping</Button></DialogFooter></form></DialogContent></Dialog>}

function ActivityLogs({logs,employees}:{logs:Log[];employees:Employee[]}){const [query,setQuery]=useState("");const visible=logs.filter(l=>`${l.entity_type} ${l.action} ${JSON.stringify(l.changes)}`.toLowerCase().includes(query.toLowerCase()));return <Card className="shadow-none"><CardHeader><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><CardTitle>Activity Logs</CardTitle><p className="mt-1 text-sm text-muted-foreground">Immutable audit trail for organisation changes.</p></div><div className="flex gap-2"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search audit trail…"/><Button variant="outline" onClick={()=>toast.success("Export queued")}><Download/>Export</Button></div></div></CardHeader><CardContent><div className="space-y-2">{visible.map(log=><div key={log.id} className="flex gap-3 rounded-xl border p-4"><span className="rounded-full bg-primary/10 p-2 text-primary"><Activity className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="text-sm"><span className="font-semibold">{employees.find(e=>e.id===log.actor_user_id)?.full_name??"Administrator"}</span> {log.action.replaceAll("_"," ")} <span className="font-medium">{log.entity_type.replaceAll("_"," ")}</span></p><p className="mt-1 truncate text-xs text-muted-foreground">{JSON.stringify(log.changes)}</p></div><time className="text-xs text-muted-foreground">{new Date(log.created_at).toLocaleString("en-IN")}</time></div>)}{!visible.length&&<Empty title="No activity yet" description="Organisation changes will appear here automatically."/>}</div></CardContent></Card>}

function Field({label,...props}:{label:string}&React.ComponentProps<typeof Input>){return <div className="space-y-1.5"><Label htmlFor={String(props.name)}>{label}</Label><Input id={String(props.name)} {...props}/></div>}
function SelectField({label,name,options,empty,defaultValue}:{label:string;name:string;options:{value:string;label:string}[];empty?:string;defaultValue?:string}){return <div className="space-y-1.5"><Label htmlFor={name}>{label}</Label><select id={name} name={name} defaultValue={defaultValue} className="h-8 w-full rounded-lg border border-input bg-background px-2.5 text-sm"><option value="">{empty??"Select…"}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>}
function Empty({title,description}:{title:string;description:string}){return <div className="p-10 text-center"><Network className="mx-auto h-9 w-9 text-muted-foreground/40"/><p className="mt-3 font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{description}</p></div>}
function initials(name:string){return name.split(" ").map(p=>p[0]).slice(0,2).join("").toUpperCase()}
