import { PayrollWorkspace, type PayrollEmployeeView, type PayrollPolicyView, type PayrollRunView, type SalaryView } from "@/components/payroll/payroll-workspace";
import { requireAdmin } from "@/lib/auth/dal";
import { createClient } from "@/lib/supabase/server";

export default async function PayrollPage({searchParams}:{searchParams:Promise<{run?:string;tab?:string}>}){
  const actor=await requireAdmin();const params=await searchParams;const supabase=await createClient();
  const [{data:runs},{data:employees},{data:departments},{data:salaries},{data:policies}]=await Promise.all([
    supabase.from("payroll_runs").select("*").eq("company_id",actor.company_id).order("period_end",{ascending:false}).limit(24),
    supabase.from("users").select("id,full_name,employee_code,department_id,work_location,employment_type,bank_details").eq("company_id",actor.company_id).neq("employment_status","archived").order("full_name"),
    supabase.from("departments").select("id,name").eq("company_id",actor.company_id),
    supabase.from("payroll_salary_structures").select("id,employee_id,name,version,monthly_fixed,effective_from,active").eq("company_id",actor.company_id).eq("active",true),
    supabase.from("payroll_policies").select("id,name,code,category,version,status,effective_from,divisor_method,sandwich_enabled").eq("company_id",actor.company_id).order("created_at",{ascending:false}),
  ]);
  const allowedTabs=new Set(["dashboard","runs","salaries","policies","slips"]);const selectedTab=params.run?"runs":allowedTabs.has(params.tab??"")?params.tab!:"dashboard";const selectedRunId=selectedTab==="runs"?params.run??null:null;const {data:results}=selectedRunId?await supabase.from("payroll_results").select("*").eq("run_id",selectedRunId).order("net_pay",{ascending:false}):{data:[]};const employeeMap=new Map((employees??[]).map(row=>[row.id,row]));const departmentMap=new Map((departments??[]).map(row=>[row.id,row.name]));
  const runViews:PayrollRunView[]=(runs??[]).map(run=>({id:run.id,number:run.run_number,type:run.run_type,status:run.status,periodStart:run.period_start,periodEnd:run.period_end,paymentDate:run.payment_date,employees:run.employee_count,gross:Number(run.gross_total),deductions:Number(run.deduction_total),net:Number(run.net_total),exceptions:run.exception_count}));
  const resultViews:PayrollEmployeeView[]=(results??[]).map(result=>{const employee=employeeMap.get(result.employee_id);return{id:result.id,employeeId:result.employee_id,name:employee?.full_name??"Former employee",code:employee?.employee_code??"—",department:employee?.department_id?departmentMap.get(employee.department_id)??"Unassigned":"Unassigned",location:employee?.work_location??"Unassigned",calendarDays:Number(result.calendar_days),present:Number(result.present_days),paidLeave:Number(result.paid_leave_days),weeklyOff:Number(result.weekly_off_days),holiday:Number(result.holiday_days),lop:Number(result.lop_days),payable:Number(result.payable_days),gross:Number(result.gross_pay),deductions:Number(result.total_deductions),net:Number(result.net_pay),status:result.status,onHold:result.on_hold,exceptions:Array.isArray(result.exceptions)?result.exceptions.map(String):[],trace:Array.isArray(result.calculation_trace)?result.calculation_trace.map(String):[]}});
  const salaryViews:SalaryView[]=(salaries??[]).map(salary=>({id:salary.id,employeeId:salary.employee_id,name:salary.name,version:salary.version,monthlyFixed:Number(salary.monthly_fixed),effectiveFrom:salary.effective_from}));
  const policyViews:PayrollPolicyView[]=(policies??[]).map(policy=>({id:policy.id,name:policy.name,code:policy.code,category:policy.category,version:policy.version,status:policy.status,effectiveFrom:policy.effective_from,divisorMethod:policy.divisor_method,sandwichEnabled:policy.sandwich_enabled}));
  return <PayrollWorkspace runs={runViews} selectedRunId={selectedRunId} selectedTab={selectedTab} results={resultViews} salaries={salaryViews} policies={policyViews} employees={(employees??[]).map(employee=>({id:employee.id,name:employee.full_name,code:employee.employee_code??"—",department:employee.department_id?departmentMap.get(employee.department_id)??"Unassigned":"Unassigned",location:employee.work_location??"Unassigned"}))} canConfigure={actor.role!=="finance"}/>;
}
