"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requirePermission } from "@/lib/permissions/access";
import type { PermissionCode } from "@/lib/permissions/catalog";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import type { Json } from "@/types/database";

export type PayrollActionResult = { ok:boolean; message:string; id?:string };
const RunSchema=z.object({month:z.string().regex(/^\d{4}-\d{2}$/),paymentDate:z.string().date(),runType:z.enum(["regular","off_cycle","arrear","full_and_final","correction"]).default("regular"),payrollGroup:z.string().trim().min(2).max(80).default("All Employees")});
const SalarySchema=z.object({employeeId:z.string().uuid(),monthlyFixed:z.number().min(0).max(100000000),effectiveFrom:z.string().date(),name:z.string().trim().min(2).max(80).default("Standard Salary"),earnings:z.record(z.string(),z.number().min(0)).default({}),deductions:z.record(z.string(),z.number().min(0)).default({})});
const PolicySchema=z.object({name:z.string().trim().min(2).max(100),code:z.string().trim().min(2).max(20),category:z.string().trim().min(2).max(80),effectiveFrom:z.string().date(),divisorMethod:z.enum(["calendar_days","fixed_30","scheduled_working_days"]),sandwichEnabled:z.boolean(),description:z.string().trim().max(500).optional()});
const amount=(value:Json|undefined)=>typeof value==="object"&&value&&!Array.isArray(value)?Object.values(value).reduce<number>((sum,item)=>sum+(typeof item==="number"?item:0),0):0;
const dates=(start:string,end:string)=>{const output:string[]=[];const cursor=new Date(`${start}T00:00:00Z`);const last=new Date(`${end}T00:00:00Z`);while(cursor<=last){output.push(cursor.toISOString().slice(0,10));cursor.setUTCDate(cursor.getUTCDate()+1)}return output};
const refresh=()=>{revalidatePath("/admin/payroll");revalidatePath("/employee/payroll");revalidatePath("/self-service/payroll")};
async function payrollAdmin(permission:PermissionCode){return requirePermission(permission)}

export async function createPayrollRun(input:z.input<typeof RunSchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("payroll.run.create");const parsed=RunSchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid payroll run."};
  const [year,month]=parsed.data.month.split("-").map(Number);const last=new Date(year,month,0).getDate();const periodStart=`${parsed.data.month}-01`,periodEnd=`${parsed.data.month}-${last}`;const supabase=createAdminClient();
  const runNumber=`PAY-${parsed.data.month.replace("-","")}-${Date.now().toString().slice(-5)}`;
  const {data,error}=await supabase.from("payroll_runs").insert({company_id:actor.company_id,run_number:runNumber,run_type:parsed.data.runType,status:"draft",period_start:periodStart,period_end:periodEnd,payment_date:parsed.data.paymentDate,attendance_cutoff:periodEnd,leave_cutoff:periodEnd,payroll_group:parsed.data.payrollGroup,created_by:actor.id}).select("id").single();
  if(error||!data)return{ok:false,message:error?.message??"Payroll run could not be created."};await supabase.from("payroll_audit_events").insert({company_id:actor.company_id,run_id:data.id,actor_user_id:actor.id,action:"run_created",new_value:parsed.data});refresh();return{ok:true,message:"Draft payroll run created.",id:data.id};
}

export async function saveSalaryStructure(input:z.input<typeof SalarySchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("salary.structure.assign");const parsed=SalarySchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid salary structure."};const supabase=await createClient();
  const rpcResult=await supabase.rpc("assign_payroll_salary_structure",{p_employee_id:parsed.data.employeeId,p_name:parsed.data.name,p_monthly_fixed:parsed.data.monthlyFixed,p_effective_from:parsed.data.effectiveFrom,p_earnings:parsed.data.earnings,p_deductions:parsed.data.deductions});
  if(!rpcResult.error){refresh();return{ok:true,message:"Salary structure saved successfully."}}
  if(rpcResult.error.code!=="PGRST202"&&!rpcResult.error.message.includes("assign_payroll_salary_structure"))return{ok:false,message:rpcResult.error.message};
  const admin=createAdminClient();const {data:employee}=await admin.from("users").select("id").eq("id",parsed.data.employeeId).eq("company_id",actor.company_id).neq("employment_status","archived").maybeSingle();if(!employee)return{ok:false,message:"Employee not found in your company."};const {data:previous}=await admin.from("payroll_salary_structures").select("*").eq("company_id",actor.company_id).eq("employee_id",employee.id).eq("active",true).order("version",{ascending:false}).limit(1).maybeSingle();const {data:latest}=await admin.from("payroll_salary_structures").select("version").eq("company_id",actor.company_id).eq("employee_id",employee.id).order("version",{ascending:false}).limit(1).maybeSingle();
  if(previous){const endDate=previous.effective_from<parsed.data.effectiveFrom?new Date(new Date(`${parsed.data.effectiveFrom}T00:00:00Z`).getTime()-86400000).toISOString().slice(0,10):previous.effective_from;const {error:updateError}=await admin.from("payroll_salary_structures").update({active:false,effective_to:endDate}).eq("id",previous.id);if(updateError)return{ok:false,message:`Could not close the previous salary version: ${updateError.message}`}}
  const {data:created,error}=await admin.from("payroll_salary_structures").insert({company_id:actor.company_id,employee_id:employee.id,name:parsed.data.name,version:(latest?.version??0)+1,monthly_fixed:parsed.data.monthlyFixed,earnings:parsed.data.earnings,deductions:parsed.data.deductions,effective_from:parsed.data.effectiveFrom,created_by:actor.id}).select("id").single();if(error||!created)return{ok:false,message:error?.message??"Salary structure could not be saved."};await admin.from("payroll_audit_events").insert({company_id:actor.company_id,employee_id:employee.id,actor_user_id:actor.id,action:"salary_structure_assigned",previous_value:previous,new_value:{id:created.id,monthly_fixed:parsed.data.monthlyFixed,effective_from:parsed.data.effectiveFrom}});refresh();return{ok:true,message:"Salary structure saved successfully."};
}

export async function savePayrollPolicy(input:z.input<typeof PolicySchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("payout.policy.create");const parsed=PolicySchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid policy."};const supabase=createAdminClient();
  const {data:latest}=await supabase.from("payroll_policies").select("version").eq("company_id",actor.company_id).eq("code",parsed.data.code.toUpperCase()).order("version",{ascending:false}).limit(1).maybeSingle();const {error}=await supabase.from("payroll_policies").insert({company_id:actor.company_id,name:parsed.data.name,code:parsed.data.code.toUpperCase(),category:parsed.data.category,description:parsed.data.description??null,version:(latest?.version??0)+1,status:"draft",effective_from:parsed.data.effectiveFrom,divisor_method:parsed.data.divisorMethod,sandwich_enabled:parsed.data.sandwichEnabled,created_by:actor.id,conditions:[],actions:[]});if(error)return{ok:false,message:error.message};refresh();return{ok:true,message:"Draft payroll policy created."};
}

export async function calculatePayrollRun(runId:string):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("payroll.run.calculate");const supabase=createAdminClient();const {data:run}=await supabase.from("payroll_runs").select("*").eq("id",runId).eq("company_id",actor.company_id).maybeSingle();if(!run)return{ok:false,message:"Payroll run not found."};if(!["draft","review_required","reopened"].includes(run.status))return{ok:false,message:"This payroll run cannot be recalculated in its current state."};
  await supabase.from("payroll_runs").update({status:"calculating",input_snapshot_at:new Date().toISOString()}).eq("id",run.id);
  const [{data:employees},{data:salaries},{data:attendance},{data:leaveDays},{data:holidays},{data:policies}]=await Promise.all([
    supabase.from("users").select("id,full_name,employee_code,date_of_joining,employment_status,department_id,work_location,bank_details").eq("company_id",actor.company_id).in("employment_status",["active","onboarding","notice_period"]).or(`date_of_joining.is.null,date_of_joining.lte.${run.period_end}`),
    supabase.from("payroll_salary_structures").select("*").eq("company_id",actor.company_id).eq("active",true).lte("effective_from",run.period_end).or(`effective_to.is.null,effective_to.gte.${run.period_start}`),
    supabase.from("attendance_records").select("id,employee_id,attendance_date,status").eq("company_id",actor.company_id).gte("attendance_date",run.period_start).lte("attendance_date",run.period_end),
    supabase.from("leave_request_days").select("leave_date,quantity,request_id,leave_requests!inner(employee_id,status)").eq("company_id",actor.company_id).gte("leave_date",run.period_start).lte("leave_date",run.period_end).eq("leave_requests.status","approved"),
    supabase.from("restricted_holidays").select("holiday_date,location").eq("company_id",actor.company_id).eq("active",true).gte("holiday_date",run.period_start).lte("holiday_date",run.period_end),
    supabase.from("payroll_policies").select("id,name,code,version,divisor_method,rounding_scale,sandwich_enabled").eq("company_id",actor.company_id).eq("status","active").lte("effective_from",run.period_end).or(`effective_to.is.null,effective_to.gte.${run.period_start}`).order("priority"),
  ]);
  await supabase.from("payroll_results").delete().eq("run_id",run.id);const allDates=dates(run.period_start,run.period_end);let grossTotal=0,deductionTotal=0,netTotal=0,exceptionCount=0;const policy=policies?.[0];
  for(const employee of employees??[]){const salary=(salaries??[]).filter(item=>item.employee_id===employee.id).sort((a,b)=>b.version-a.version)[0];const exceptions:string[]=[];if(!salary)exceptions.push("Missing salary structure");const bank=employee.bank_details;if(!bank||typeof bank!=="object"||Array.isArray(bank)||!Object.keys(bank).length)exceptions.push("Bank/payment details require review");const eligibleDates=allDates.filter(date=>!employee.date_of_joining||date>=employee.date_of_joining);let present=0,paidLeave=0,weeklyOff=0,holiday=0,lop=0;const dayDrafts:{date:string;source:string;final:string;fraction:number;attendanceId:string|null;leaveId:string|null}[]=[];
    for(const date of eligibleDates){const att=(attendance??[]).find(item=>item.employee_id===employee.id&&item.attendance_date===date);const leave=(leaveDays??[]).find(item=>item.leave_date===date&&(item.leave_requests as unknown as {employee_id:string}).employee_id===employee.id);const isHoliday=(holidays??[]).some(item=>item.holiday_date===date&&(item.location==="All locations"||item.location===employee.work_location));const day=new Date(`${date}T00:00:00Z`).getUTCDay();let source="Attendance Pending",final="Attendance Pending",fraction=0;
      if(date<employee.date_of_joining!){source=final="Not Joined"}else if(leave){source=final="Paid Leave";fraction=Number(leave.quantity);paidLeave+=fraction}else if(isHoliday){source=final="Holiday";fraction=1;holiday++}else if(day===0||day===6){source=final="Weekly Off";fraction=1;weeklyOff++}else if(att){source=att.status; if(["present","work_from_home","field_work"].includes(att.status)){final=att.status==="work_from_home"?"Work From Home":"Present";fraction=1;present++}else if(att.status==="half_day"){final="Half Day Present";fraction=.5;present+=.5;lop+=.5}else if(att.status==="on_leave"){final="Paid Leave";fraction=1;paidLeave++}else{final="Absent";lop++}}else{exceptions.push(`Attendance pending: ${date}`);lop++}
      dayDrafts.push({date,source,final,fraction,attendanceId:att?.id??null,leaveId:leave?.request_id??null});
    }
    const divisor=policy?.divisor_method==="fixed_30"?30:policy?.divisor_method==="scheduled_working_days"?Math.max(1,eligibleDates.filter(date=>![0,6].includes(new Date(`${date}T00:00:00Z`).getUTCDay())).length):allDates.length;const payable=Math.max(0,Math.min(eligibleDates.length,eligibleDates.length-lop));const fixed=salary?Number((Number(salary.monthly_fixed)*payable/divisor).toFixed(policy?.rounding_scale??2)):0;const otherEarnings=salary?amount(salary.earnings):0;const otherDeductions=salary?amount(salary.deductions):0;const gross=fixed+otherEarnings;const net=Math.max(0,gross-otherDeductions);const {data:result,error}=await supabase.from("payroll_results").insert({company_id:actor.company_id,run_id:run.id,employee_id:employee.id,salary_structure_id:salary?.id??null,salary_structure_version:salary?.version??null,calendar_days:allDates.length,eligible_days:eligibleDates.length,present_days:present,paid_leave_days:paidLeave,weekly_off_days:weeklyOff,holiday_days:holiday,lop_days:lop,payable_days:payable,divisor,fixed_earnings:fixed,other_earnings:otherEarnings,gross_pay:gross,other_deductions:otherDeductions,total_deductions:otherDeductions,net_pay:net,status:exceptions.length?"exception":"calculated",exceptions,input_snapshot:{employee,salary,policy,calculatedAt:new Date().toISOString()},calculation_trace:[`Eligible ${eligibleDates.length} days`,`LOP ${lop} days`,`Payable ${payable} days`,`Fixed earning = ${salary?.monthly_fixed??0} × ${payable} ÷ ${divisor}`]}).select("id").single();if(error||!result)continue;
    await supabase.from("payroll_day_results").insert(dayDrafts.map(item=>({company_id:actor.company_id,result_id:result.id,employee_id:employee.id,payroll_date:item.date,source_classification:item.source,final_classification:item.final,paid_fraction:item.fraction,attendance_record_id:item.attendanceId,leave_request_id:item.leaveId,policy_result:{}})));grossTotal+=gross;deductionTotal+=otherDeductions;netTotal+=net;exceptionCount+=exceptions.length?1:0;
  }
  await supabase.from("payroll_runs").update({status:"review_required",employee_count:(employees??[]).length,gross_total:grossTotal,deduction_total:deductionTotal,net_total:netTotal,exception_count:exceptionCount,policy_snapshot:policies??[]}).eq("id",run.id);await supabase.from("payroll_audit_events").insert({company_id:actor.company_id,run_id:run.id,actor_user_id:actor.id,action:"run_calculated",new_value:{employeeCount:(employees??[]).length,grossTotal,netTotal,exceptionCount}});refresh();return{ok:true,message:`Calculated ${(employees??[]).length} employee payouts.`};
}

export async function transitionPayrollRun(runId:string,action:"approve"|"lock"|"mark_paid"|"publish",reference?:string):Promise<PayrollActionResult>{
  const actionPermission:Record<typeof action,PermissionCode>={approve:"payroll.run.approve",lock:"payroll.run.lock",mark_paid:"payroll.payment.mark_paid",publish:"salary_slip.publish"};const actor=await payrollAdmin(actionPermission[action]);const supabase=createAdminClient();const {data:run}=await supabase.from("payroll_runs").select("*").eq("id",runId).eq("company_id",actor.company_id).maybeSingle();if(!run)return{ok:false,message:"Payroll run not found."};const allowed:Record<string,[string,string]>={approve:["review_required","approved"],lock:["approved","locked"],mark_paid:["locked","paid"],publish:["paid","published"]};const [from,to]=allowed[action];if(run.status!==from)return{ok:false,message:`Run must be ${from.replaceAll("_"," ")} before this action.`};if(action==="approve"&&run.exception_count>0)return{ok:false,message:"Resolve critical exceptions before approval."};const update:{status:string;approved_by?:string;approved_at?:string;locked_by?:string;locked_at?:string;paid_at?:string;payment_reference?:string;published_at?:string}={status:to};if(action==="approve"){update.approved_by=actor.id;update.approved_at=new Date().toISOString()}if(action==="lock"){update.locked_by=actor.id;update.locked_at=new Date().toISOString()}if(action==="mark_paid"){if(!reference?.trim())return{ok:false,message:"Payment reference is required."};update.paid_at=new Date().toISOString();update.payment_reference=reference.trim()}if(action==="publish")update.published_at=new Date().toISOString();const {error}=await supabase.from("payroll_runs").update(update).eq("id",run.id);if(error)return{ok:false,message:error.message};
  if(action==="publish"){const {data:results}=await supabase.from("payroll_results").select("*").eq("run_id",run.id);for(const result of results??[])await supabase.from("payroll_slips").insert({company_id:actor.company_id,run_id:run.id,result_id:result.id,employee_id:result.employee_id,status:"published",snapshot:{run,result},published_at:new Date().toISOString(),published_by:actor.id});}
  await supabase.from("payroll_audit_events").insert({company_id:actor.company_id,run_id:run.id,actor_user_id:actor.id,action:`run_${action}`,previous_value:{status:run.status},new_value:{status:to,reference}});refresh();return{ok:true,message:`Payroll run ${to.replaceAll("_"," ")}.`};
}
