"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requirePermission } from "@/lib/permissions/access";
import type { PermissionCode } from "@/lib/permissions/catalog";
import { buildSalarySlipPdf } from "@/lib/payroll/salary-slip-pdf";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import type { Json } from "@/types/database";
import { calculateSalary, type SalaryComponentRule } from "@/lib/payroll/calculation-engine";

export type PayrollActionResult = { ok:boolean; message:string; id?:string };
const RunSchema=z.object({month:z.string().regex(/^\d{4}-\d{2}$/),paymentDate:z.string().date(),runType:z.enum(["regular","off_cycle","arrear","full_and_final","correction"]).default("regular"),payrollGroup:z.string().trim().min(2).max(80).default("All Employees")});
const SalarySchema=z.object({employeeId:z.string().uuid(),monthlyFixed:z.number().min(0).max(100000000),effectiveFrom:z.string().date(),name:z.string().trim().min(2).max(80).default("Standard Salary"),earnings:z.record(z.string(),z.number().min(0)).default({}),deductions:z.record(z.string(),z.number().min(0)).default({})});
const CodeSchema=z.string().trim().min(2).max(30).regex(/^[A-Za-z][A-Za-z0-9_-]*$/,"Code must start with a letter and contain only letters, numbers, hyphens, or underscores.");
const ComponentSchema=z.object({name:z.string().trim().min(2).max(100),code:CodeSchema,componentType:z.enum(["earning","employee_deduction","employer_contribution","reimbursement","informational"]),calculationMethod:z.enum(["fixed","percentage_of_ctc","percentage_of_gross","percentage_of_component","percentage_of_components","balancing","manual"]),fixedAmount:z.number().min(0).optional(),percentage:z.number().min(0).max(1000).optional(),baseComponentCodes:z.array(z.string()).default([]),minimumAmount:z.number().min(0).optional(),maximumAmount:z.number().min(0).optional(),priority:z.number().int().min(0).max(10000).default(100),includeInGross:z.boolean().default(false),includeInNet:z.boolean().default(false),includeInCtc:z.boolean().default(false),prorate:z.boolean().default(true),allowEmployeeOverride:z.boolean().default(false),showOnSalarySlip:z.boolean().default(true),effectiveFrom:z.string().date(),status:z.enum(["draft","active"]).default("active")}).refine(v=>v.minimumAmount===undefined||v.maximumAmount===undefined||v.minimumAmount<=v.maximumAmount,{message:"Minimum amount cannot exceed maximum amount."}).refine(v=>!v.calculationMethod.startsWith("percentage")||v.percentage!==undefined,{message:"Percentage is required."}).refine(v=>!["percentage_of_component","percentage_of_components"].includes(v.calculationMethod)||v.baseComponentCodes.length>0,{message:"Select at least one base component."});
const TemplateSchema=z.object({name:z.string().trim().min(2).max(100),code:CodeSchema,description:z.string().trim().max(500).optional(),salaryInputType:z.enum(["annual_ctc","monthly_ctc","monthly_gross","basic","manual"]),componentIds:z.array(z.string().uuid()).min(1),effectiveFrom:z.string().date(),status:z.enum(["draft","active"]).default("active")});
const DynamicSalarySchema=z.object({employeeId:z.string().uuid(),templateId:z.string().uuid(),monthlyCtc:z.number().positive().max(100000000),effectiveFrom:z.string().date(),revisionReason:z.string().trim().min(3).max(300),overrides:z.record(z.string(),z.number().min(0).max(100000000)).default({})});
const EditComponentSchema=ComponentSchema.extend({id:z.string().uuid(),changeReason:z.string().trim().min(3).max(300)});
const EditTemplateSchema=TemplateSchema.extend({id:z.string().uuid(),changeReason:z.string().trim().min(3).max(300)});
const PolicySchema=z.object({name:z.string().trim().min(2).max(100),code:z.string().trim().min(2).max(20),category:z.string().trim().min(2).max(80),effectiveFrom:z.string().date(),divisorMethod:z.enum(["calendar_days","fixed_30","scheduled_working_days"]),sandwichEnabled:z.boolean(),description:z.string().trim().max(500).optional()});
const amount=(value:Json|undefined)=>typeof value==="object"&&value&&!Array.isArray(value)?Object.values(value).reduce<number>((sum,item)=>sum+(typeof item==="number"?item:0),0):0;
const dates=(start:string,end:string)=>{const output:string[]=[];const cursor=new Date(`${start}T00:00:00Z`);const last=new Date(`${end}T00:00:00Z`);while(cursor<=last){output.push(cursor.toISOString().slice(0,10));cursor.setUTCDate(cursor.getUTCDate()+1)}return output};
const refresh=()=>{revalidatePath("/admin/payroll");revalidatePath("/employee/payroll");revalidatePath("/self-service/payroll")};
async function payrollAdmin(permission:PermissionCode){return requirePermission(permission)}

export async function getSalaryCatalog(){const actor=await payrollAdmin("salary.structure.view");const db=createAdminClient();const [{data:componentRows},{data:templateRows}]=await Promise.all([db.from("salary_components").select("*").eq("company_id",actor.company_id).in("status",["active","draft"]).order("priority"),db.from("salary_structure_templates").select("*").eq("company_id",actor.company_id).in("status",["active","draft"]).order("created_at",{ascending:false})]);const components=(componentRows??[]).map(row=>({...componentToRule(row),version:row.version,status:row.status,effectiveFrom:row.effective_from}));const templates=(templateRows??[]).map(row=>({id:row.id,name:row.name,code:row.code,version:row.version,salaryInputType:row.salary_input_type,status:row.status,effectiveFrom:row.effective_from,components:row.component_rules as unknown as SalaryComponentRule[]}));return{ok:true,components,templates}}

export async function saveSalaryComponent(input:z.input<typeof ComponentSchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("salary.structure.create");const parsed=ComponentSchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid salary component."};const db=createAdminClient();const value=parsed.data;const code=value.code.toUpperCase();
  const {data:latest}=await db.from("salary_components").select("id,version,status").eq("company_id",actor.company_id).eq("code",code).order("version",{ascending:false}).limit(1).maybeSingle();if(latest&&["active","scheduled"].includes(latest.status))return{ok:false,message:"An active component with this code already exists. Create a new version to change it."};
  const {data,error}=await db.from("salary_components").insert({company_id:actor.company_id,root_id:latest?.id??null,version:(latest?.version??0)+1,name:value.name,code,component_type:value.componentType,calculation_method:value.calculationMethod,fixed_amount:value.fixedAmount??null,percentage:value.percentage??null,base_component_codes:value.baseComponentCodes.map(x=>x.toUpperCase()),minimum_amount:value.minimumAmount??null,maximum_amount:value.maximumAmount??null,priority:value.priority,include_in_gross:value.includeInGross,include_in_net:value.includeInNet,include_in_ctc:value.includeInCtc,prorate:value.prorate,allow_employee_override:value.allowEmployeeOverride,show_on_salary_slip:value.showOnSalarySlip,effective_from:value.effectiveFrom,status:value.status,created_by:actor.id}).select("id").single();if(error||!data)return{ok:false,message:error?.message??"Component could not be saved."};await db.from("payroll_audit_events").insert({company_id:actor.company_id,actor_user_id:actor.id,action:"salary_component_created",new_value:{...value,code}});refresh();return{ok:true,message:`${value.name} created.`,id:data.id};
}

export async function saveSalaryTemplate(input:z.input<typeof TemplateSchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("salary.structure.create");const parsed=TemplateSchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid salary template."};const db=createAdminClient();const value=parsed.data;const {data:components}=await db.from("salary_components").select("*").eq("company_id",actor.company_id).in("id",value.componentIds).eq("status","active");if((components??[]).length!==value.componentIds.length)return{ok:false,message:"One or more selected components are inactive or unavailable."};const rules=(components??[]).map(component=>componentToRule(component));const validation=calculateSalary({monthlyCtc:100000,targetGross:100000,payableDays:30,divisor:30,components:rules});if(validation.errors.some(error=>error.startsWith("Circular")))return{ok:false,message:validation.errors[0]};const code=value.code.toUpperCase();const {data:latest}=await db.from("salary_structure_templates").select("id,version,status").eq("company_id",actor.company_id).eq("code",code).order("version",{ascending:false}).limit(1).maybeSingle();if(latest&&["active","scheduled"].includes(latest.status))return{ok:false,message:"An active template with this code already exists."};const {data,error}=await db.from("salary_structure_templates").insert({company_id:actor.company_id,root_id:latest?.id??null,version:(latest?.version??0)+1,name:value.name,code,description:value.description??null,salary_input_type:value.salaryInputType,component_rules:rules as unknown as Json,effective_from:value.effectiveFrom,status:value.status,created_by:actor.id}).select("id").single();if(error||!data)return{ok:false,message:error?.message??"Template could not be saved."};await db.from("payroll_audit_events").insert({company_id:actor.company_id,actor_user_id:actor.id,action:"salary_template_created",new_value:{name:value.name,code,components:value.componentIds}});refresh();return{ok:true,message:`${value.name} template created.`,id:data.id};
}

export async function editSalaryComponent(input:z.input<typeof EditComponentSchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("salary.structure.edit");const parsed=EditComponentSchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid component changes."};const db=createAdminClient();const value=parsed.data;const {data:current}=await db.from("salary_components").select("*").eq("id",value.id).eq("company_id",actor.company_id).maybeSingle();if(!current)return{ok:false,message:"Salary component not found."};const code=value.code.toUpperCase();const payload={name:value.name,code,component_type:value.componentType,calculation_method:value.calculationMethod,fixed_amount:value.fixedAmount??null,percentage:value.percentage??null,base_component_codes:value.baseComponentCodes.map(x=>x.toUpperCase()),minimum_amount:value.minimumAmount??null,maximum_amount:value.maximumAmount??null,priority:value.priority,include_in_gross:value.includeInGross,include_in_net:value.includeInNet,include_in_ctc:value.includeInCtc,prorate:value.prorate,allow_employee_override:value.allowEmployeeOverride,show_on_salary_slip:value.showOnSalarySlip,effective_from:value.effectiveFrom};
  if(current.status==="draft"){const {error}=await db.from("salary_components").update({...payload,status:value.status}).eq("id",current.id);if(error)return{ok:false,message:error.message};await db.from("payroll_audit_events").insert({company_id:actor.company_id,actor_user_id:actor.id,action:"salary_component_draft_edited",previous_value:current,new_value:payload,reason:value.changeReason});refresh();return{ok:true,message:"Component draft updated."}}
  const {data:created,error:createError}=await db.from("salary_components").insert({company_id:actor.company_id,root_id:current.root_id??current.id,version:current.version+1,...payload,status:"draft",created_by:actor.id}).select("id").single();if(createError||!created)return{ok:false,message:createError?.message??"New component version could not be created."};const priorDay=new Date(new Date(`${value.effectiveFrom}T00:00:00Z`).getTime()-86400000).toISOString().slice(0,10);const {error:closeError}=await db.from("salary_components").update({status:"archived",effective_to:priorDay<current.effective_from?current.effective_from:priorDay}).eq("id",current.id);if(closeError)return{ok:false,message:closeError.message};const {error:activateError}=await db.from("salary_components").update({status:value.status}).eq("id",created.id);if(activateError){await db.from("salary_components").update({status:current.status,effective_to:current.effective_to}).eq("id",current.id);return{ok:false,message:activateError.message}}await db.from("payroll_audit_events").insert({company_id:actor.company_id,actor_user_id:actor.id,action:"salary_component_version_created",previous_value:current,new_value:{id:created.id,version:current.version+1,...payload},reason:value.changeReason});refresh();return{ok:true,message:`${value.name} version ${current.version+1} created.`};
}

export async function editSalaryTemplate(input:z.input<typeof EditTemplateSchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("salary.structure.edit");const parsed=EditTemplateSchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid template changes."};const db=createAdminClient();const value=parsed.data;const [{data:current},{data:components}]=await Promise.all([db.from("salary_structure_templates").select("*").eq("id",value.id).eq("company_id",actor.company_id).maybeSingle(),db.from("salary_components").select("*").eq("company_id",actor.company_id).in("id",value.componentIds).eq("status","active")]);if(!current)return{ok:false,message:"Salary template not found."};if((components??[]).length!==value.componentIds.length)return{ok:false,message:"Every selected component must be active."};const rules=(components??[]).map(componentToRule);const validation=calculateSalary({monthlyCtc:100000,targetGross:100000,payableDays:30,divisor:30,components:rules});if(validation.errors.some(error=>error.startsWith("Circular")))return{ok:false,message:validation.errors[0]};const payload={name:value.name,code:value.code.toUpperCase(),description:value.description??null,salary_input_type:value.salaryInputType,component_rules:rules as unknown as Json,effective_from:value.effectiveFrom};
  if(current.status==="draft"){const {error}=await db.from("salary_structure_templates").update({...payload,status:value.status}).eq("id",current.id);if(error)return{ok:false,message:error.message};await db.from("payroll_audit_events").insert({company_id:actor.company_id,actor_user_id:actor.id,action:"salary_template_draft_edited",previous_value:current,new_value:payload,reason:value.changeReason});refresh();return{ok:true,message:"Template draft updated."}}
  const {data:created,error:createError}=await db.from("salary_structure_templates").insert({company_id:actor.company_id,root_id:current.root_id??current.id,version:current.version+1,...payload,status:"draft",created_by:actor.id}).select("id").single();if(createError||!created)return{ok:false,message:createError?.message??"New template version could not be created."};const priorDay=new Date(new Date(`${value.effectiveFrom}T00:00:00Z`).getTime()-86400000).toISOString().slice(0,10);const {error:closeError}=await db.from("salary_structure_templates").update({status:"archived",effective_to:priorDay<current.effective_from?current.effective_from:priorDay}).eq("id",current.id);if(closeError)return{ok:false,message:closeError.message};const {error:activateError}=await db.from("salary_structure_templates").update({status:value.status}).eq("id",created.id);if(activateError){await db.from("salary_structure_templates").update({status:current.status,effective_to:current.effective_to}).eq("id",current.id);return{ok:false,message:activateError.message}}await db.from("payroll_audit_events").insert({company_id:actor.company_id,actor_user_id:actor.id,action:"salary_template_version_created",previous_value:current,new_value:{id:created.id,version:current.version+1,...payload},reason:value.changeReason});refresh();return{ok:true,message:`${value.name} version ${current.version+1} created.`};
}

export async function assignDynamicSalaryStructure(input:z.input<typeof DynamicSalarySchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("salary.structure.assign");const parsed=DynamicSalarySchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid salary assignment."};const db=createAdminClient();const value=parsed.data;const [{data:employee},{data:template}]=await Promise.all([db.from("users").select("id").eq("id",value.employeeId).eq("company_id",actor.company_id).neq("employment_status","archived").maybeSingle(),db.from("salary_structure_templates").select("*").eq("id",value.templateId).eq("company_id",actor.company_id).eq("status","active").maybeSingle()]);if(!employee)return{ok:false,message:"Employee not found."};if(!template)return{ok:false,message:"Active salary template not found."};const rules=template.component_rules as unknown as SalaryComponentRule[];const invalidOverrides=Object.keys(value.overrides).filter(code=>!rules.some(rule=>rule.code===code&&rule.allowEmployeeOverride));if(invalidOverrides.length)return{ok:false,message:`Override is not permitted for: ${invalidOverrides.join(", ")}.`};const preview=calculateSalary({monthlyCtc:value.monthlyCtc,targetGross:value.monthlyCtc,payableDays:30,divisor:30,components:rules,overrides:value.overrides});if(preview.errors.length)return{ok:false,message:preview.errors[0]};const {data:previous}=await db.from("payroll_salary_structures").select("*").eq("company_id",actor.company_id).eq("employee_id",employee.id).eq("active",true).order("version",{ascending:false}).limit(1).maybeSingle();const {data:latest}=await db.from("payroll_salary_structures").select("version").eq("company_id",actor.company_id).eq("employee_id",employee.id).order("version",{ascending:false}).limit(1).maybeSingle();if(previous){if(value.effectiveFrom<=previous.effective_from)return{ok:false,message:"The revision effective date must be after the current salary version."};const priorDay=new Date(new Date(`${value.effectiveFrom}T00:00:00Z`).getTime()-86400000).toISOString().slice(0,10);const {error}=await db.from("payroll_salary_structures").update({active:false,effective_to:priorDay,workflow_status:"superseded"}).eq("id",previous.id);if(error)return{ok:false,message:error.message}}
  const {data:created,error}=await db.from("payroll_salary_structures").insert({company_id:actor.company_id,employee_id:employee.id,name:template.name,version:(latest?.version??0)+1,monthly_fixed:preview.gross,monthly_ctc:value.monthlyCtc,monthly_gross:preview.gross,earnings:{},deductions:{},template_id:template.id,component_snapshot:rules as unknown as Json,component_overrides:value.overrides,workflow_status:"active",revision_reason:value.revisionReason,effective_from:value.effectiveFrom,created_by:actor.id}).select("id").single();if(error||!created)return{ok:false,message:error?.message??"Salary could not be assigned."};await db.from("payroll_audit_events").insert({company_id:actor.company_id,employee_id:employee.id,actor_user_id:actor.id,action:"dynamic_salary_assigned",previous_value:previous,new_value:{id:created.id,template_id:template.id,monthly_ctc:value.monthlyCtc,preview},reason:value.revisionReason});refresh();return{ok:true,message:"Dynamic salary structure assigned.",id:created.id};
}

function componentToRule(component:{id:string;code:string;name:string;component_type:string;calculation_method:string;fixed_amount:number|null;percentage:number|null;base_component_codes:string[];minimum_amount:number|null;maximum_amount:number|null;prorate:boolean;include_in_gross:boolean;include_in_net:boolean;include_in_ctc:boolean;priority:number;allow_negative:boolean;allow_employee_override:boolean}):SalaryComponentRule{return{id:component.id,code:component.code,name:component.name,type:component.component_type as SalaryComponentRule["type"],method:component.calculation_method as SalaryComponentRule["method"],fixedAmount:component.fixed_amount??undefined,percentage:component.percentage??undefined,baseComponentCodes:component.base_component_codes,minimumAmount:component.minimum_amount??undefined,maximumAmount:component.maximum_amount??undefined,prorate:component.prorate,includeInGross:component.include_in_gross,includeInNet:component.include_in_net,includeInCtc:component.include_in_ctc,priority:component.priority,allowNegative:component.allow_negative,allowEmployeeOverride:component.allow_employee_override} as SalaryComponentRule & {allowEmployeeOverride:boolean}}

export async function createPayrollRun(input:z.input<typeof RunSchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("payroll.run.create");const parsed=RunSchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid payroll run."};
  const [year,month]=parsed.data.month.split("-").map(Number);const last=new Date(year,month,0).getDate();const periodStart=`${parsed.data.month}-01`,periodEnd=`${parsed.data.month}-${last}`;const supabase=createAdminClient();
  const runNumber=`PAY-${parsed.data.month.replace("-","")}-${Date.now().toString().slice(-5)}`;
  const {data,error}=await supabase.from("payroll_runs").insert({company_id:actor.company_id,run_number:runNumber,run_type:parsed.data.runType,status:"draft",period_start:periodStart,period_end:periodEnd,payment_date:parsed.data.paymentDate,attendance_cutoff:periodEnd,leave_cutoff:periodEnd,payroll_group:parsed.data.payrollGroup,created_by:actor.id}).select("id").single();
  if(error||!data)return{ok:false,message:error?.message??"Payroll run could not be created."};await supabase.from("payroll_audit_events").insert({company_id:actor.company_id,run_id:data.id,actor_user_id:actor.id,action:"run_created",new_value:parsed.data});refresh();return{ok:true,message:"Draft payroll run created.",id:data.id};
}

export async function saveSalaryStructure(input:z.input<typeof SalarySchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("salary.structure.assign");const parsed=SalarySchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid salary structure."};const supabase=await createClient();
  const rpcResult=await supabase.rpc("assign_payroll_salary_structure",{p_employee_id:parsed.data.employeeId,p_name:parsed.data.name,p_monthly_fixed:parsed.data.monthlyFixed,p_effective_from:parsed.data.effectiveFrom,p_earnings:parsed.data.earnings,p_deductions:parsed.data.deductions});
  if(!rpcResult.error){refresh();return{ok:true,message:"Salary structure saved successfully."}}
  if(rpcResult.error.code!=="PGRST202"&&!rpcResult.error.message.includes("assign_payroll_salary_structure"))return{ok:false,message:rpcResult.error.message};
  const admin=createAdminClient();const {data:employee}=await admin.from("users").select("id").eq("id",parsed.data.employeeId).eq("company_id",actor.company_id).neq("employment_status","archived").maybeSingle();if(!employee)return{ok:false,message:"Employee not found in your company."};const {data:previous}=await admin.from("payroll_salary_structures").select("*").eq("company_id",actor.company_id).eq("employee_id",employee.id).eq("active",true).order("version",{ascending:false}).limit(1).maybeSingle();const {data:latest}=await admin.from("payroll_salary_structures").select("version").eq("company_id",actor.company_id).eq("employee_id",employee.id).order("version",{ascending:false}).limit(1).maybeSingle();
  if(previous){const endDate=previous.effective_from<parsed.data.effectiveFrom?new Date(new Date(`${parsed.data.effectiveFrom}T00:00:00Z`).getTime()-86400000).toISOString().slice(0,10):previous.effective_from;const {error:updateError}=await admin.from("payroll_salary_structures").update({active:false,effective_to:endDate}).eq("id",previous.id);if(updateError)return{ok:false,message:`Could not close the previous salary version: ${updateError.message}`}}
  const {data:created,error}=await admin.from("payroll_salary_structures").insert({company_id:actor.company_id,employee_id:employee.id,name:parsed.data.name,version:(latest?.version??0)+1,monthly_fixed:parsed.data.monthlyFixed,earnings:parsed.data.earnings,deductions:parsed.data.deductions,effective_from:parsed.data.effectiveFrom,created_by:actor.id}).select("id").single();if(error||!created)return{ok:false,message:error?.message??"Salary structure could not be saved."};await admin.from("payroll_audit_events").insert({company_id:actor.company_id,employee_id:employee.id,actor_user_id:actor.id,action:"salary_structure_assigned",previous_value:previous,new_value:{id:created.id,monthly_fixed:parsed.data.monthlyFixed,effective_from:parsed.data.effectiveFrom}});refresh();return{ok:true,message:"Salary structure saved successfully."};
}

export async function savePayrollPolicy(input:z.input<typeof PolicySchema>):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("payout.policy.create");const parsed=PolicySchema.safeParse(input);if(!parsed.success)return{ok:false,message:parsed.error.issues[0]?.message??"Invalid policy."};const supabase=createAdminClient();
  const {data:latest}=await supabase.from("payroll_policies").select("version").eq("company_id",actor.company_id).eq("code",parsed.data.code.toUpperCase()).order("version",{ascending:false}).limit(1).maybeSingle();const {error}=await supabase.from("payroll_policies").insert({company_id:actor.company_id,name:parsed.data.name,code:parsed.data.code.toUpperCase(),category:parsed.data.category,description:parsed.data.description??null,version:(latest?.version??0)+1,status:"draft",effective_from:parsed.data.effectiveFrom,divisor_method:parsed.data.divisorMethod,sandwich_enabled:parsed.data.sandwichEnabled,created_by:actor.id,conditions:[],actions:[]});if(error)return{ok:false,message:error.message};refresh();return{ok:true,message:"Draft payroll policy created."};
}

export async function calculatePayrollRun(runId:string):Promise<PayrollActionResult>{
  const actor=await payrollAdmin("payroll.run.calculate");const supabase=createAdminClient();const {data:run}=await supabase.from("payroll_runs").select("*").eq("id",runId).eq("company_id",actor.company_id).maybeSingle();if(!run)return{ok:false,message:"Payroll run not found."};if(!["draft","review_required","reopened"].includes(run.status))return{ok:false,message:"This payroll run cannot be recalculated in its current state."};
  await supabase.from("payroll_runs").update({status:"calculating",input_snapshot_at:new Date().toISOString()}).eq("id",run.id);
  const [{data:employees},{data:salaries},{data:attendance},{data:leaveDays},{data:holidays},{data:policies}]=await Promise.all([
    supabase.from("users").select("id,full_name,employee_code,date_of_joining,employment_status,department_id,work_location,bank_details").eq("company_id",actor.company_id).in("employment_status",["active","onboarding","notice_period"]).or(`date_of_joining.is.null,date_of_joining.lte.${run.period_end}`),
    supabase.from("payroll_salary_structures").select("*").eq("company_id",actor.company_id).eq("active",true).lte("effective_from",run.period_end).or(`effective_to.is.null,effective_to.gte.${run.period_start}`),
    supabase.from("attendance_records").select("id,employee_id,attendance_date,status").eq("company_id",actor.company_id).gte("attendance_date",run.period_start).lte("attendance_date",run.period_end),
    supabase.from("leave_request_days").select("leave_date,quantity,request_id,leave_requests!inner(employee_id,status)").eq("company_id",actor.company_id).gte("leave_date",run.period_start).lte("leave_date",run.period_end).eq("leave_requests.status","approved"),
    supabase.from("restricted_holidays").select("holiday_date,location").eq("company_id",actor.company_id).eq("active",true).gte("holiday_date",run.period_start).lte("holiday_date",run.period_end),
    supabase.from("payroll_policies").select("id,name,code,version,divisor_method,rounding_scale,sandwich_enabled").eq("company_id",actor.company_id).eq("status","active").lte("effective_from",run.period_end).or(`effective_to.is.null,effective_to.gte.${run.period_start}`).order("priority"),
  ]);
  await supabase.from("payroll_results").delete().eq("run_id",run.id);const allDates=dates(run.period_start,run.period_end);let grossTotal=0,deductionTotal=0,netTotal=0,exceptionCount=0;const policy=policies?.[0];
  for(const employee of employees??[]){const salary=(salaries??[]).filter(item=>item.employee_id===employee.id).sort((a,b)=>b.version-a.version)[0];const exceptions:string[]=[];if(!salary)exceptions.push("Missing salary structure");const bank=employee.bank_details;if(!bank||typeof bank!=="object"||Array.isArray(bank)||!Object.keys(bank).length)exceptions.push("Bank/payment details require review");const eligibleDates=allDates.filter(date=>!employee.date_of_joining||date>=employee.date_of_joining);let present=0,paidLeave=0,weeklyOff=0,holiday=0,lop=0;const dayDrafts:{date:string;source:string;final:string;fraction:number;attendanceId:string|null;leaveId:string|null}[]=[];
    for(const date of eligibleDates){const att=(attendance??[]).find(item=>item.employee_id===employee.id&&item.attendance_date===date);const leave=(leaveDays??[]).find(item=>item.leave_date===date&&(item.leave_requests as unknown as {employee_id:string}).employee_id===employee.id);const isHoliday=(holidays??[]).some(item=>item.holiday_date===date&&(item.location==="All locations"||item.location===employee.work_location));const day=new Date(`${date}T00:00:00Z`).getUTCDay();let source="Attendance Pending",final="Attendance Pending",fraction=0;
      if(date<employee.date_of_joining!){source=final="Not Joined"}else if(leave){source=final="Paid Leave";fraction=Number(leave.quantity);paidLeave+=fraction}else if(isHoliday){source=final="Holiday";fraction=1;holiday++}else if(day===0||day===6){source=final="Weekly Off";fraction=1;weeklyOff++}else if(att){source=att.status; if(["present","work_from_home","field_work"].includes(att.status)){final=att.status==="work_from_home"?"Work From Home":"Present";fraction=1;present++}else if(att.status==="half_day"){final="Half Day Present";fraction=.5;present+=.5;lop+=.5}else if(att.status==="on_leave"){final="Paid Leave";fraction=1;paidLeave++}else{final="Absent";lop++}}else{exceptions.push(`Attendance pending: ${date}`);lop++}
      dayDrafts.push({date,source,final,fraction,attendanceId:att?.id??null,leaveId:leave?.request_id??null});
    }
    const divisor=policy?.divisor_method==="fixed_30"?30:policy?.divisor_method==="scheduled_working_days"?Math.max(1,eligibleDates.filter(date=>![0,6].includes(new Date(`${date}T00:00:00Z`).getUTCDay())).length):allDates.length;const payable=Math.max(0,Math.min(eligibleDates.length,eligibleDates.length-lop));const snapshot=Array.isArray(salary?.component_snapshot)?salary.component_snapshot as unknown as SalaryComponentRule[]:[];const dynamic=salary&&snapshot.length?calculateSalary({monthlyCtc:Number(salary.monthly_ctc??salary.monthly_fixed),targetGross:Number(salary.monthly_gross??salary.monthly_fixed),payableDays:payable,divisor,components:snapshot,overrides:(salary.component_overrides&&typeof salary.component_overrides==="object"&&!Array.isArray(salary.component_overrides)?salary.component_overrides:{}) as Record<string,number>}):null;if(dynamic?.errors.length)exceptions.push(...dynamic.errors);const fixed=dynamic?dynamic.components.filter(item=>item.type==="earning").reduce((sum,item)=>sum+item.payableAmount,0):salary?Number((Number(salary.monthly_fixed)*payable/divisor).toFixed(policy?.rounding_scale??2)):0;const otherEarnings=dynamic?0:salary?amount(salary.earnings):0;const otherDeductions=dynamic?dynamic.deductions:salary?amount(salary.deductions):0;const gross=dynamic?dynamic.gross:fixed+otherEarnings;const net=Math.max(0,dynamic?dynamic.net:gross-otherDeductions);const {data:result,error}=await supabase.from("payroll_results").insert({company_id:actor.company_id,run_id:run.id,employee_id:employee.id,salary_structure_id:salary?.id??null,salary_structure_version:salary?.version??null,calendar_days:allDates.length,eligible_days:eligibleDates.length,present_days:present,paid_leave_days:paidLeave,weekly_off_days:weeklyOff,holiday_days:holiday,lop_days:lop,payable_days:payable,divisor,fixed_earnings:fixed,other_earnings:otherEarnings,reimbursements:dynamic?.reimbursements??0,employer_contributions:dynamic?.employerContributions??0,component_results:(dynamic?.components??[]) as unknown as Json,gross_pay:gross,other_deductions:otherDeductions,total_deductions:otherDeductions,net_pay:net,status:exceptions.length?"exception":"calculated",exceptions,input_snapshot:{employee,salary,policy,calculatedAt:new Date().toISOString()},calculation_trace:dynamic?[`Eligible ${eligibleDates.length} days`,`LOP ${lop} days`,`Payable ${payable} days`,...dynamic.trace]:[`Eligible ${eligibleDates.length} days`,`LOP ${lop} days`,`Payable ${payable} days`,`Fixed earning = ${salary?.monthly_fixed??0} × ${payable} ÷ ${divisor}`]}).select("id").single();if(error||!result)continue;
    await supabase.from("payroll_day_results").insert(dayDrafts.map(item=>({company_id:actor.company_id,result_id:result.id,employee_id:employee.id,payroll_date:item.date,source_classification:item.source,final_classification:item.final,paid_fraction:item.fraction,attendance_record_id:item.attendanceId,leave_request_id:item.leaveId,policy_result:{}})));grossTotal+=gross;deductionTotal+=otherDeductions;netTotal+=net;exceptionCount+=exceptions.length?1:0;
  }
  await supabase.from("payroll_runs").update({status:"review_required",employee_count:(employees??[]).length,gross_total:grossTotal,deduction_total:deductionTotal,net_total:netTotal,exception_count:exceptionCount,policy_snapshot:policies??[]}).eq("id",run.id);await supabase.from("payroll_audit_events").insert({company_id:actor.company_id,run_id:run.id,actor_user_id:actor.id,action:"run_calculated",new_value:{employeeCount:(employees??[]).length,grossTotal,netTotal,exceptionCount}});refresh();return{ok:true,message:`Calculated ${(employees??[]).length} employee payouts.`};
}

export async function transitionPayrollRun(runId:string,action:"approve"|"lock"|"mark_paid"|"publish",reference?:string):Promise<PayrollActionResult>{
  const actionPermission:Record<typeof action,PermissionCode>={approve:"payroll.run.approve",lock:"payroll.run.lock",mark_paid:"payroll.payment.mark_paid",publish:"salary_slip.publish"};const actor=await payrollAdmin(actionPermission[action]);const supabase=createAdminClient();const {data:run}=await supabase.from("payroll_runs").select("*").eq("id",runId).eq("company_id",actor.company_id).maybeSingle();if(!run)return{ok:false,message:"Payroll run not found."};const allowed:Record<string,[string,string]>={approve:["review_required","approved"],lock:["approved","locked"],mark_paid:["locked","paid"],publish:["paid","published"]};const [from,to]=allowed[action];if(run.status!==from)return{ok:false,message:`Run must be ${from.replaceAll("_"," ")} before this action.`};if(action==="approve"&&run.exception_count>0){if(actor.role!=="super_admin")return{ok:false,message:"Resolve critical exceptions before approval."};if(!reference?.trim())return{ok:false,message:"An override reason is required to approve payroll with exceptions."}}const update:{status:string;approved_by?:string;approved_at?:string;locked_by?:string;locked_at?:string;paid_at?:string;payment_reference?:string;published_at?:string}={status:to};if(action==="approve"){update.approved_by=actor.id;update.approved_at=new Date().toISOString()}if(action==="lock"){update.locked_by=actor.id;update.locked_at=new Date().toISOString()}if(action==="mark_paid"){if(!reference?.trim())return{ok:false,message:"Payment reference is required."};update.paid_at=new Date().toISOString();update.payment_reference=reference.trim()}if(action==="publish")update.published_at=new Date().toISOString();const {error}=await supabase.from("payroll_runs").update(update).eq("id",run.id);if(error)return{ok:false,message:error.message};
  if(action==="publish"){const [{data:results},{data:company}]=await Promise.all([supabase.from("payroll_results").select("*").eq("run_id",run.id),supabase.from("companies").select("name").eq("id",actor.company_id).single()]);for(const result of results??[]){const {data:employee}=await supabase.from("users").select("full_name,employee_code").eq("id",result.employee_id).eq("company_id",actor.company_id).single();if(!employee)continue;const {data:slip,error:slipError}=await supabase.from("payroll_slips").insert({company_id:actor.company_id,run_id:run.id,result_id:result.id,employee_id:result.employee_id,status:"published",snapshot:{run,result,employee,company},published_at:new Date().toISOString(),published_by:actor.id}).select("id,version").single();if(slipError||!slip)continue;const pdf=buildSalarySlipPdf({companyName:company?.name??"Company",employeeName:employee.full_name,employeeCode:employee.employee_code??"—",periodStart:run.period_start,periodEnd:run.period_end,paymentDate:run.payment_date,runNumber:run.run_number,gross:Number(result.gross_pay),deductions:Number(result.total_deductions),net:Number(result.net_pay),payableDays:Number(result.payable_days),lopDays:Number(result.lop_days),paymentReference:run.payment_reference});const path=`${actor.company_id}/${result.employee_id}/${slip.id}-v${slip.version}.pdf`;const {error:uploadError}=await supabase.storage.from("salary-slips").upload(path,pdf,{contentType:"application/pdf",upsert:true});if(!uploadError)await supabase.from("payroll_slips").update({storage_path:path}).eq("id",slip.id);await supabase.from("payroll_audit_events").insert({company_id:actor.company_id,run_id:run.id,result_id:result.id,employee_id:result.employee_id,actor_user_id:actor.id,action:uploadError?"salary_slip_pdf_failed":"salary_slip_pdf_generated",new_value:uploadError?{error:uploadError.message}:{storage_path:path}})}}
  await supabase.from("payroll_audit_events").insert({company_id:actor.company_id,run_id:run.id,actor_user_id:actor.id,action:`run_${action}`,previous_value:{status:run.status},new_value:{status:to,reference},reason:action==="approve"&&run.exception_count>0?reference?.trim():null});refresh();return{ok:true,message:action==="approve"&&run.exception_count>0?"Payroll approved with a recorded exception override.":`Payroll run ${to.replaceAll("_"," ")}.`};
}
