import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BriefcaseBusiness, CalendarDays, CheckCircle2, Clock, FileText, Mail, MapPin, MoreHorizontal, Pencil, ShieldCheck, UserRound, Users } from "lucide-react";
import { requireAdmin } from "@/lib/auth/dal";
import { createClient } from "@/lib/supabase/server";
import { changeEmployeeStatus } from "@/lib/employees/actions";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

function title(value: string | null) {
  return value ? value.replaceAll("_", " ").replace(/\b\w/g, (char) => char.toUpperCase()) : "Not provided";
}

function Info({ label, value }: { label: string; value: React.ReactNode }) {
  return <div><p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><div className="mt-1 text-sm font-medium text-foreground">{value || "Not provided"}</div></div>;
}

export default async function EmployeeProfilePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string }> }) {
  const admin = await requireAdmin();
  const { id } = await params;
  const query = await searchParams;
  const supabase = await createClient();
  const { data: employee } = await supabase.from("users").select("*").eq("id", id).eq("company_id", admin.company_id).maybeSingle();
  if (!employee) notFound();
  const [{ data: department }, { data: designation }, { data: manager }, { data: reports }, { data: activity }] = await Promise.all([
    employee.department_id ? supabase.from("departments").select("name").eq("id", employee.department_id).maybeSingle() : Promise.resolve({ data: null }),
    employee.designation_id ? supabase.from("designations").select("name").eq("id", employee.designation_id).maybeSingle() : Promise.resolve({ data: null }),
    employee.reporting_manager_id ? supabase.from("users").select("id, full_name").eq("id", employee.reporting_manager_id).maybeSingle() : Promise.resolve({ data: null }),
    supabase.from("users").select("id, full_name, employee_code").eq("reporting_manager_id", employee.id).eq("company_id", admin.company_id).limit(8),
    supabase.from("audit_logs").select("id, action, changes, created_at").eq("entity_id", employee.id).eq("company_id", admin.company_id).order("created_at", { ascending: false }).limit(10),
  ]);
  const initials = employee.full_name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  const currentAddress = (employee.current_address ?? {}) as Record<string, string | null>;
  const emergency = (employee.emergency_contact ?? {}) as Record<string, string | null>;
  const bank = (employee.bank_details ?? {}) as Record<string, string | null>;
  const statutory = (employee.statutory_details ?? {}) as Record<string, string | null>;
  const maskedAccount = bank.accountNumber ? `•••• ${bank.accountNumber.slice(-4)}` : null;
  const maskedAadhaar = statutory.aadhaarNumber ? `•••• •••• ${statutory.aadhaarNumber.slice(-4)}` : null;

  return (
    <div className="space-y-5">
      <Link href="/admin/employees" className="inline-flex items-center gap-1.5 text-sm font-medium text-muted-foreground hover:text-primary"><ArrowLeft className="h-4 w-4" />Back to employees</Link>
      {query.created === "1" && <div className="flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><CheckCircle2 className="h-5 w-5" /><span><strong>Employee created successfully.</strong> The record and access configuration are ready.</span></div>}

      <Card className="overflow-hidden border-border/80 bg-white shadow-none"><div className="h-24 bg-gradient-to-r from-[#6d41e9] via-[#7448ee] to-[#3788f5]" /><CardContent className="px-6 pb-6"><div className="-mt-10 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><Avatar className="h-24 w-24 border-4 border-white shadow-md"><AvatarFallback className="bg-primary text-xl font-bold text-white">{initials}</AvatarFallback></Avatar><div className="pb-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-bold text-foreground">{employee.full_name}</h2><Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700">{title(employee.employment_status)}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{designation?.name ?? "No designation"} · {department?.name ?? "No department"}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground"><span>{employee.employee_code}</span><span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{employee.work_location ?? "No location"}</span><span className="flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5" />Joined {employee.date_of_joining ? new Date(employee.date_of_joining).toLocaleDateString("en-IN") : "—"}</span></div></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" className="gap-2"><Mail className="h-4 w-4" />Send Message</Button><Button nativeButton={false} render={<Link href={`/admin/employees/${employee.id}/edit`} />} variant="outline" className="gap-2"><Pencil className="h-4 w-4" />Edit Profile</Button><Button variant="outline" size="icon"><MoreHorizontal className="h-4 w-4" /></Button></div></div><div className="mt-5 grid gap-4 border-t border-border pt-5 sm:grid-cols-2 lg:grid-cols-4"><Info label="Reporting Manager" value={manager ? <Link href={`/admin/employees/${manager.id}`} className="text-primary hover:underline">{manager.full_name}</Link> : "Not assigned"} /><Info label="Employment Type" value={title(employee.employment_type)} /><Info label="Work Mode" value={title(employee.work_mode)} /><div><div className="flex justify-between text-xs"><span className="font-semibold text-foreground">Profile completion</span><span>{employee.profile_completion}%</span></div><Progress value={employee.profile_completion} className="mt-2" /></div></div></CardContent></Card>

      <Tabs defaultValue="overview" className="gap-5"><TabsList variant="line" className="w-full justify-start overflow-x-auto rounded-xl border border-border bg-white px-3">{["overview", "personal", "employment", "attendance", "leave", "documents", "assets", "payroll", "activity"].map((tab) => <TabsTrigger key={tab} value={tab} className="capitalize">{tab}</TabsTrigger>)}</TabsList>
        <TabsContent value="overview" className="space-y-5"><div className="grid gap-5 lg:grid-cols-3"><Card className="border-border/80 shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><BriefcaseBusiness className="h-4 w-4 text-primary" />Employment Information</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><Info label="Employee ID" value={employee.employee_code} /><Info label="Department" value={department?.name} /><Info label="Designation" value={designation?.name} /><Info label="Team / Grade" value={[employee.team_name, employee.grade].filter(Boolean).join(" · ")} /></CardContent></Card><Card className="border-border/80 shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><UserRound className="h-4 w-4 text-primary" />Contact Information</CardTitle></CardHeader><CardContent className="space-y-4"><Info label="Official Email" value={employee.email} /><Info label="Mobile" value={employee.mobile_number} /><Info label="Personal Email" value={employee.personal_email} /><Info label="Address" value={[currentAddress.line1, currentAddress.city, currentAddress.state, currentAddress.pinCode].filter(Boolean).join(", ")} /></CardContent></Card><Card className="border-border/80 shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Users className="h-4 w-4 text-primary" />Reporting Structure</CardTitle></CardHeader><CardContent className="space-y-3"><div className="rounded-lg bg-muted/50 p-3 text-center text-sm">{manager?.full_name ?? "No reporting manager"}</div><div className="text-center text-primary">↓</div><div className="rounded-lg border border-primary/20 bg-primary/5 p-3 text-center text-sm font-semibold text-primary">{employee.full_name}</div>{reports?.length ? <><div className="text-center text-primary">↓</div><div className="space-y-2">{reports.map((report) => <Link key={report.id} href={`/admin/employees/${report.id}`} className="block rounded-lg border border-border p-2 text-center text-xs hover:border-primary/30">{report.full_name}</Link>)}</div></> : <p className="text-center text-xs text-muted-foreground">No direct reports</p>}</CardContent></Card></div><div className="grid gap-5 sm:grid-cols-3">{[{ title: "Attendance Summary", value: "Not checked in", icon: Clock }, { title: "Leave Balance", value: "Available after leave setup", icon: CalendarDays }, { title: "Pending Actions", value: employee.profile_completion < 100 ? "Complete employee profile" : "No pending actions", icon: ShieldCheck }].map((item) => <Card key={item.title} className="border-border/80 shadow-none"><CardContent className="flex items-center gap-4 p-5"><span className="rounded-xl bg-primary/10 p-3 text-primary"><item.icon className="h-5 w-5" /></span><div><p className="text-xs text-muted-foreground">{item.title}</p><p className="mt-1 text-sm font-semibold text-foreground">{item.value}</p></div></CardContent></Card>)}</div></TabsContent>
        <TabsContent value="personal"><Card className="border-border/80 shadow-none"><CardHeader><CardTitle>Personal & Contact Details</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Info label="Date of Birth" value={employee.date_of_birth ? new Date(employee.date_of_birth).toLocaleDateString("en-IN") : null} /><Info label="Gender" value={title(employee.gender)} /><Info label="Marital Status" value={title(employee.marital_status)} /><Info label="Blood Group" value={employee.blood_group} /><Info label="Emergency Contact" value={emergency.name} /><Info label="Relationship" value={emergency.relationship} /><Info label="Emergency Mobile" value={emergency.mobile} /></CardContent></Card></TabsContent>
        <TabsContent value="employment"><div className="grid gap-5 lg:grid-cols-2"><Card className="border-border/80 shadow-none"><CardHeader><CardTitle>Employment Details</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Info label="Status" value={title(employee.employment_status)} /><Info label="Type" value={title(employee.employment_type)} /><Info label="Work Mode" value={title(employee.work_mode)} /><Info label="Shift" value={employee.shift_name} /><Info label="Notice Period" value={employee.notice_period_days ? `${employee.notice_period_days} days` : null} /><Info label="Cost Centre" value={employee.cost_centre} /></CardContent></Card><Card className="border-border/80 shadow-none"><CardHeader><CardTitle>Bank & Statutory (masked)</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Info label="Bank" value={bank.bankName} /><Info label="Account" value={maskedAccount} /><Info label="IFSC" value={bank.ifscCode} /><Info label="PAN" value={statutory.panNumber} /><Info label="Aadhaar" value={maskedAadhaar} /><Info label="UAN" value={statutory.uanNumber} /></CardContent></Card></div></TabsContent>
        <TabsContent value="attendance"><Placeholder icon={Clock} title="Attendance" description="Daily check-ins, effective hours, late arrivals, and attendance history will appear here." /></TabsContent><TabsContent value="leave"><Placeholder icon={CalendarDays} title="Leave" description="Leave balances, applications, and approval history will appear here." /></TabsContent><TabsContent value="documents"><Placeholder icon={FileText} title="Documents" description="Secure employee documents and verification status will appear here." /></TabsContent><TabsContent value="assets"><Placeholder icon={BriefcaseBusiness} title="Assets — Phase 2" description="Assigned devices and company assets will appear here." /></TabsContent><TabsContent value="payroll"><Placeholder icon={ShieldCheck} title="Payroll — Phase 2" description="Salary structure and payroll records are intentionally restricted." /></TabsContent>
        <TabsContent value="activity"><Card className="border-border/80 shadow-none"><CardHeader><CardTitle>Activity Log</CardTitle></CardHeader><CardContent>{activity?.length ? <div className="space-y-3">{activity.map((item) => <div key={item.id} className="flex items-start justify-between gap-4 border-b border-border pb-3 text-sm"><div><p className="font-medium text-foreground">{title(item.action)}</p><p className="text-xs text-muted-foreground">Employee record activity</p></div><time className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString("en-IN")}</time></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">No activity recorded yet.</p>}</CardContent></Card></TabsContent>
      </Tabs>

      <Card className="border-border/80 bg-white shadow-none"><CardContent className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><h3 className="font-semibold text-foreground">Employment status</h3><p className="text-sm text-muted-foreground">Status changes preserve attendance, leave, payroll, and audit history.</p></div><form action={changeEmployeeStatus} className="flex gap-2"><input type="hidden" name="employeeId" value={employee.id} /><select name="status" defaultValue={employee.employment_status} className="h-10 rounded-lg border border-input bg-white px-3 text-sm">{["active", "onboarding", "notice_period", "inactive", "resigned", "terminated", "archived"].map((item) => <option key={item} value={item}>{title(item)}</option>)}</select><Button type="submit" variant="outline">Update Status</Button></form></CardContent></Card>
    </div>
  );
}

function Placeholder({ icon: Icon, title: heading, description }: { icon: React.ComponentType<{ className?: string }>; title: string; description: string }) {
  return <Card className="border-border/80 shadow-none"><CardContent className="py-14 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-6 w-6" /></span><h3 className="mt-4 font-semibold text-foreground">{heading}</h3><p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">{description}</p></CardContent></Card>;
}
