"use client";

import { useEffect, useState, useTransition } from "react";
import { CalendarDays, CheckCircle2, Clock3, FileClock, LogIn, LogOut, MapPin, Timer, Wifi } from "lucide-react";
import { toast } from "sonner";
import { AttendanceStatusBadge } from "@/components/attendance/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { punchAttendance, submitRegularization } from "@/lib/attendance/actions";

export type EmployeeAttendanceDay = { day: number; status: string; checkIn: string; checkOut: string; grossMinutes: number; breakMinutes: number; minutes: number; overtimeMinutes: number; lateMinutes: number; earlyMinutes: number; source: string };
export type EmployeeRequestView = { type: string; date: string; requested: string; status: string };
export type EmployeeAttendanceSummary = { present: number; minutes: number; late: number; pending: number };

export function EmployeeAttendanceWorkspace({ employeeName, shiftName, shiftTiming, timezone, initialCheckedIn = false, calendarRecords = [], initialRequests = [], summary }: { employeeName: string; shiftName: string; shiftTiming: string; timezone: string; initialCheckedIn?: boolean; calendarRecords?: EmployeeAttendanceDay[]; initialRequests?: EmployeeRequestView[]; summary: EmployeeAttendanceSummary }) {
  const [now,setNow]=useState<Date|null>(null);
  const [checkedIn,setCheckedIn]=useState(initialCheckedIn);
  const [selected,setSelected]=useState(new Date().getDate());
  const [activeTab,setActiveTab]=useState("calendar");
  const [showRequestForm,setShowRequestForm]=useState(false);
  const [requestType,setRequestType]=useState("Missed check-out");
  const [requestDate,setRequestDate]=useState(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date()));
  const [requestedTime,setRequestedTime]=useState("18:00");
  const [reason,setReason]=useState("");
  const [requestItems,setRequestItems]=useState(initialRequests);
  const [pending,startTransition]=useTransition();
  useEffect(()=>{const id=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(id)},[]);
  const selectedRecord=calendarRecords.find((record)=>record.day===selected);
  const daysInMonth=new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate();
  const days=Array.from({length:daysInMonth},(_,index)=>index+1);
  const monthLabel=new Date().toLocaleDateString("en-IN",{month:"long",year:"numeric"});
  const punch=()=>startTransition(async()=>{const result=await punchAttendance(checkedIn?"out":"in");if(!result.ok){toast.error(result.message);return}setCheckedIn((value)=>!value);toast.success(result.message)});
  const submitRequest=(event:React.FormEvent)=>{event.preventDefault();startTransition(async()=>{const result=await submitRegularization({attendanceDate:requestDate,requestType,requestedCheckOut:requestedTime,reason});if(!result.ok){toast.error(result.message);return}setRequestItems((items)=>[{type:requestType,date:new Date(`${requestDate}T00:00:00`).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}),requested:requestedTime,status:"Pending"},...items]);setReason("");setShowRequestForm(false);toast.success(result.message)})};

  return <div className="space-y-6">
    <div><p className="text-sm font-medium text-primary">Employee self-service</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-foreground">My attendance</h2><p className="mt-1 text-sm text-muted-foreground">{employeeName} · Track your workday, hours, and attendance requests.</p></div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_1fr]">
      <Card className="relative overflow-hidden bg-gradient-to-br from-[#4f20b5] to-primary text-white ring-0"><div className="absolute -right-12 -top-12 h-52 w-52 rounded-full bg-white/10"/><CardContent className="relative p-6 sm:p-8"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-white/70">{new Date().toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</p><p className="mt-2 font-mono text-4xl font-semibold tracking-tight sm:text-5xl">{now?now.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",second:"2-digit"}):"--:--:--"}</p><div className="mt-4 flex flex-wrap gap-2"><Badge className="border-white/15 bg-white/10 text-white"><Wifi/>Network verified by server</Badge><Badge className="border-white/15 bg-white/10 text-white"><MapPin/>Attendance location</Badge></div></div><div className="text-right"><p className="text-xs text-white/60">Assigned shift</p><p className="mt-1 font-semibold">{shiftName} · {shiftTiming}</p></div></div><div className="mt-10 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-wider text-white/60">Today&apos;s status</p><p className="mt-1 text-lg font-semibold">{checkedIn?"Currently checked in":"Not checked in"}</p></div><Button size="lg" onClick={punch} disabled={pending} className="h-12 bg-white px-6 text-primary hover:bg-white/90">{pending?"Saving…":checkedIn?<><LogOut/>Check out</>:<><LogIn/>Check in</>}</Button></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Today&apos;s timeline</CardTitle><CardDescription>Calculated in {timezone}</CardDescription></CardHeader><CardContent>{selectedRecord?<AttendanceMetrics record={selectedRecord}/>:<p className="py-10 text-center text-muted-foreground">No attendance record for today.</p>}</CardContent></Card>
    </div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Present days",String(summary.present),"This month",CheckCircle2,"text-emerald-600 bg-emerald-50"],["Effective hours",`${Math.floor(summary.minutes/60)}h ${summary.minutes%60}m`,"This month",Clock3,"text-primary bg-accent"],["Late arrivals",String(summary.late),"This month",Timer,"text-amber-600 bg-amber-50"],["Pending requests",String(summary.pending),"Awaiting review",FileClock,"text-sky-600 bg-sky-50"]].map(([label,value,sub,Icon,color])=>{const C=Icon as typeof Clock3;return <Card key={String(label)}><CardContent className="flex items-center gap-4 p-5"><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${color}`}><C/></span><div><p className="text-xl font-semibold text-foreground">{String(value)}</p><p className="text-sm font-medium text-foreground">{String(label)}</p><p className="text-xs text-muted-foreground">{String(sub)}</p></div></CardContent></Card>})}</div>
    <div className="space-y-4"><div className="inline-flex rounded-lg bg-muted p-1" role="tablist"><button type="button" onClick={()=>setActiveTab("calendar")} className={`rounded-md px-3 py-1.5 text-sm font-medium ${activeTab==="calendar"?"bg-card text-foreground shadow-sm":"text-muted-foreground"}`}>Calendar</button><button type="button" onClick={()=>setActiveTab("requests")} className={`rounded-md px-3 py-1.5 text-sm font-medium ${activeTab==="requests"?"bg-card text-foreground shadow-sm":"text-muted-foreground"}`}>Regularization</button></div>
      {activeTab==="calendar"&&<Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle>{monthLabel}</CardTitle><CardDescription>Only stored attendance records are shown</CardDescription></div><Button variant="outline"><CalendarDays/>{monthLabel}</Button></div></CardHeader><CardContent><div className="grid gap-5 lg:grid-cols-[1fr_280px]"><div><div className="grid grid-cols-7 text-center text-xs font-medium text-muted-foreground">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day)=><span key={day} className="py-2">{day}</span>)}</div><div className="grid grid-cols-7 gap-1">{days.map((day)=>{const record=calendarRecords.find((item)=>item.day===day);return <button type="button" key={day} onClick={()=>setSelected(day)} className={`min-h-16 rounded-lg border p-1.5 text-left sm:min-h-20 ${selected===day?"border-primary bg-accent/50":"bg-card"}`}><span className="text-xs font-medium text-foreground">{day}</span>{record&&<span className="mt-2 block w-fit rounded bg-emerald-50 px-1.5 py-0.5 text-[10px] font-semibold text-emerald-700">{record.status}</span>}</button>})}</div></div><div className="rounded-xl border bg-muted/20 p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{selected} {monthLabel}</p>{selectedRecord?<><div className="mt-2"><AttendanceStatusBadge status={selectedRecord.status}/></div><div className="mt-5"><AttendanceMetrics record={selectedRecord}/></div></>:<p className="mt-5 text-sm text-muted-foreground">No attendance record exists for this date.</p>}</div></div></CardContent></Card>}
      {activeTab==="requests"&&<Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Regularization requests</CardTitle><CardDescription>Requests stored in your company database</CardDescription></div><Button onClick={()=>setShowRequestForm((value)=>!value)}><FileClock/>{showRequestForm?"Cancel":"New request"}</Button></div></CardHeader><CardContent className="space-y-4">{showRequestForm&&<form onSubmit={submitRequest} className="grid gap-4 rounded-xl border bg-muted/20 p-4 sm:grid-cols-2"><label className="text-sm font-medium">Request type<select value={requestType} onChange={(event)=>setRequestType(event.target.value)} className="mt-1 h-9 w-full rounded-lg border bg-card px-3"><option>Missed check-in</option><option>Missed check-out</option><option>Incorrect check-in</option><option>Incorrect check-out</option><option>Work from home</option></select></label><label className="text-sm font-medium">Attendance date<input type="date" value={requestDate} onChange={(event)=>setRequestDate(event.target.value)} className="mt-1 h-9 w-full rounded-lg border bg-card px-3" required/></label><label className="text-sm font-medium">Requested time<input type="time" value={requestedTime} onChange={(event)=>setRequestedTime(event.target.value)} className="mt-1 h-9 w-full rounded-lg border bg-card px-3" required/></label><label className="text-sm font-medium">Reason<input value={reason} onChange={(event)=>setReason(event.target.value)} className="mt-1 h-9 w-full rounded-lg border bg-card px-3" required/></label><div className="sm:col-span-2 flex justify-end"><Button type="submit" disabled={pending}><CheckCircle2/>{pending?"Submitting…":"Submit request"}</Button></div></form>}{requestItems.map((item,index)=><div key={`${item.date}-${index}`} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><p className="font-medium text-foreground">{item.type} · {item.date}</p><p className="mt-1 text-sm text-muted-foreground">Requested: {item.requested}</p></div><AttendanceStatusBadge status={item.status}/></div></div>)}{requestItems.length===0&&!showRequestForm&&<p className="py-10 text-center text-muted-foreground">No regularization requests found.</p>}</CardContent></Card>}
    </div>
  </div>;
}

function duration(minutes: number) { return minutes ? `${Math.floor(minutes / 60) ? `${Math.floor(minutes / 60)} hr ` : ""}${minutes % 60} min`.trim() : "—"; }
function AttendanceMetrics({ record }: { record: EmployeeAttendanceDay }) { return <div className="space-y-3">{[["Check-in",record.checkIn],["Check-out",record.checkOut],["Late by",duration(record.lateMinutes)],["Gross hours",record.checkOut === "—" ? "In progress" : duration(record.grossMinutes)],["Break duration",duration(record.breakMinutes)],["Effective hours",record.checkOut === "—" ? "In progress" : duration(record.minutes)],["Early departure",duration(record.earlyMinutes)],["Overtime",duration(record.overtimeMinutes)],["Source",record.source]].map(([label,value])=><div key={label} className="flex items-center justify-between border-b pb-2 last:border-0"><span className="text-sm text-muted-foreground">{label}</span><b className="text-sm text-foreground">{value}</b></div>)}</div>; }
