"use client";

import { useEffect, useMemo, useRef, useState, useSyncExternalStore } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Download, LockKeyhole, Search, TriangleAlert, UserCheck, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

export type AttendanceDayDetail = { date: string; code: string; status: string; checkIn: string; checkOut: string; lateMinutes: number; grossMinutes: number; breakMinutes: number; effectiveMinutes: number; overtimeMinutes: number; regularization: string };
export type AttendanceMatrixRow = { employeeId: string; employeeCode: string; name: string; department: string; location: string; shift: string; shiftTiming: string; days: AttendanceDayDetail[]; present: number; absent: number; leave: number; wfh: number; late: number; grossMinutes: number; effectiveMinutes: number; overtimeMinutes: number; pendingRegularizations: number };

const statusStyle: Record<string, string> = { P:"border-emerald-200 bg-emerald-50 text-emerald-700", A:"border-rose-200 bg-rose-50 text-rose-700", L:"border-sky-200 bg-sky-50 text-sky-700", WFH:"border-violet-200 bg-violet-50 text-violet-700", HD:"border-orange-200 bg-orange-50 text-orange-700", WO:"border-slate-200 bg-slate-100 text-slate-600", H:"border-cyan-200 bg-cyan-50 text-cyan-700", "—":"border-slate-200 bg-slate-50 text-slate-400" };
const legend = [["P","Present"],["A","Absent"],["L","Leave"],["WFH","Work from home"],["HD","Half day"],["WO","Weekly off"],["H","Holiday"],["—","No record"]];
const hours = (minutes: number) => `${Math.floor(minutes / 60)}h ${minutes % 60}m`;

export function MonthlyAttendance({ rows, selectedMonth, today, locked, onLock }: { rows: AttendanceMatrixRow[]; selectedMonth: string; today: string; locked: boolean; onLock: () => void }) {
  const router = useRouter();
  const [query,setQuery] = useState(""); const [department,setDepartment] = useState(""); const [location,setLocation] = useState(""); const [shift,setShift] = useState(""); const [status,setStatus] = useState("");
  const [rangeStart,setRangeStart] = useState(() => selectedMonth === today.slice(0,7) ? Math.floor((Number(today.slice(-2)) - 1) / 7) * 7 + 1 : 1); const [fullMonth,setFullMonth] = useState(true); const [selectedEmployee,setSelectedEmployee] = useState<AttendanceMatrixRow | null>(null);
  const topScroll = useRef<HTMLDivElement>(null); const tableScroll = useRef<HTMLDivElement>(null); const syncing = useRef(false);
  const daysInMonth = rows[0]?.days.length ?? new Date(Number(selectedMonth.slice(0,4)),Number(selectedMonth.slice(5,7)),0).getDate();
  const monthDate = new Date(`${selectedMonth}-01T00:00:00`); const isCurrentMonth = selectedMonth === today.slice(0,7); const todayDay = isCurrentMonth ? Number(today.slice(-2)) : 0;
  const smallScreen = useSyncExternalStore((notify) => { const media=window.matchMedia("(max-width: 767px)"); media.addEventListener("change",notify); return()=>media.removeEventListener("change",notify); }, () => window.matchMedia("(max-width: 767px)").matches, () => false);
  const effectiveFullMonth = fullMonth && !smallScreen;
  useEffect(() => { if (!effectiveFullMonth || !todayDay) return; requestAnimationFrame(() => { if (tableScroll.current) tableScroll.current.scrollLeft = Math.max(0, (todayDay - 1) * 54 - tableScroll.current.clientWidth / 2); if (topScroll.current && tableScroll.current) topScroll.current.scrollLeft = tableScroll.current.scrollLeft; }); }, [effectiveFullMonth,todayDay]);
  const visibleDays = effectiveFullMonth ? Array.from({length:daysInMonth},(_,i)=>i+1) : Array.from({length:Math.min(7,daysInMonth-rangeStart+1)},(_,i)=>rangeStart+i);
  const unique = (key: "department"|"location"|"shift") => [...new Set(rows.map((row)=>row[key]))].sort();
  const filtered = useMemo(() => rows.filter((row) => `${row.name} ${row.employeeCode}`.toLowerCase().includes(query.toLowerCase()) && (!department || row.department===department) && (!location || row.location===location) && (!shift || row.shift===shift) && (!status || row.days.some((day)=>day.code===status))), [rows,query,department,location,shift,status]);
  const totalEffective = filtered.reduce((sum,row)=>sum+row.effectiveMinutes,0); const workingRecords = filtered.reduce((sum,row)=>sum+row.days.filter((day)=>!["—","WO","H"].includes(day.code)).length,0); const presentRecords = filtered.reduce((sum,row)=>sum+row.present,0);
  const presentToday = isCurrentMonth ? filtered.filter((row) => row.days[todayDay - 1]?.checkIn !== "—").length : "—";
  const kpis = [["Total Employees",filtered.length,"In selected view",Users,"text-primary bg-accent"],["Average Attendance",`${workingRecords?Math.round(presentRecords/workingRecords*100):0}%`,"Recorded working days",UserCheck,"text-emerald-700 bg-emerald-50"],["Present Today",presentToday,isCurrentMonth?"Employees who checked in":"Current month only",UserCheck,"text-emerald-700 bg-emerald-50"],["Employees on Leave",isCurrentMonth?filtered.filter((row)=>row.days[todayDay-1]?.code==="L").length:filtered.reduce((sum,row)=>sum+row.leave,0),isCurrentMonth?"Today":"Leave days",CalendarDays,"text-sky-700 bg-sky-50"],["Attendance Exceptions",filtered.reduce((sum,row)=>sum+row.absent+row.late+row.pendingRegularizations,0),"Absent, late or pending",TriangleAlert,"text-orange-700 bg-orange-50"],["Total Effective Hours",hours(totalEffective),"Selected month",Clock3,"text-violet-700 bg-violet-50"]] as const;
  const navigateMonth = (offset:number) => { const date=new Date(Number(selectedMonth.slice(0,4)),Number(selectedMonth.slice(5,7))-1+offset,1); router.push(`/admin/attendance?tab=monthly&month=${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`); };
  const sync = (source:"top"|"table") => { if(syncing.current)return; syncing.current=true; const from=source==="top"?topScroll.current:tableScroll.current; const to=source==="top"?tableScroll.current:topScroll.current; if(from&&to)to.scrollLeft=from.scrollLeft; requestAnimationFrame(()=>{syncing.current=false}); };
  const exportRows = () => { const columns=["Employee",...Array.from({length:daysInMonth},(_,i)=>String(i+1)),"Present","Absent","Leave","WFH","Late Days","Effective Hours"]; const csv=[columns,...filtered.map(row=>[row.name,...row.days.map(day=>day.code),String(row.present),String(row.absent),String(row.leave),String(row.wfh),String(row.late),hours(row.effectiveMinutes)])].map(line=>line.map(value=>`"${value.replaceAll('"','""')}"`).join(",")).join("\n"); const link=document.createElement("a"); link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"})); link.download=`attendance-${selectedMonth}.csv`; link.click(); URL.revokeObjectURL(link.href); };

  return <TooltipProvider><div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-sm font-medium text-primary">Attendance calendar</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Monthly Attendance</h2><p className="mt-1 text-sm text-muted-foreground">Review every employee and every date without losing context.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={exportRows}><Download/>Export Attendance</Button><Button variant={locked?"outline":"default"} onClick={onLock}><LockKeyhole/>{locked?"Unlock Month":"Lock Month"}</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{kpis.map(([label,value,sub,Icon,color])=><Card key={label}><CardContent className="flex items-center gap-3 p-4"><span className={`flex size-9 shrink-0 items-center justify-center rounded-lg ${color}`}><Icon className="size-4"/></span><div className="min-w-0"><p className="truncate text-lg font-semibold">{value}</p><p className="truncate text-xs font-medium">{label}</p><p className="truncate text-[11px] text-muted-foreground">{sub}</p></div></CardContent></Card>)}</div>
    <Card><CardContent className="space-y-4 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-1"><Button variant="outline" size="icon" aria-label="Previous month" onClick={()=>navigateMonth(-1)}><ChevronLeft/></Button><div className="flex h-9 min-w-40 items-center justify-center rounded-lg border bg-background px-3 text-sm font-semibold">{monthDate.toLocaleDateString("en-IN",{month:"long",year:"numeric"})}</div><Button variant="outline" size="icon" aria-label="Next month" onClick={()=>navigateMonth(1)}><ChevronRight/></Button></div><div className="flex rounded-lg bg-muted p-1"><button onClick={()=>setFullMonth(false)} className={`rounded-md px-3 py-1.5 text-xs font-medium ${!effectiveFullMonth?"bg-card shadow-sm":"text-muted-foreground"}`}>Weekly View</button><button onClick={()=>setFullMonth(true)} className={`hidden rounded-md px-3 py-1.5 text-xs font-medium md:block ${effectiveFullMonth?"bg-card shadow-sm":"text-muted-foreground"}`}>Full Month View</button></div></div>
      <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-5"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee" className="pl-9"/></div><FilterSelect label="All departments" value={department} options={unique("department")} onChange={setDepartment}/><FilterSelect label="All locations" value={location} options={unique("location")} onChange={setLocation}/><FilterSelect label="All shifts" value={shift} options={unique("shift")} onChange={setShift}/><FilterSelect label="All statuses" value={status} options={legend.slice(0,-1).map(item=>item[0])} onChange={setStatus}/></div>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t pt-4"><div className="flex flex-wrap gap-1">{Array.from({length:Math.ceil(daysInMonth/7)},(_,index)=>{const start=index*7+1,end=Math.min(daysInMonth,start+6);return <button key={start} onClick={()=>{setFullMonth(false);setRangeStart(start)}} className={`rounded-md px-2.5 py-1.5 text-xs font-medium ${!effectiveFullMonth&&rangeStart===start?"bg-primary text-primary-foreground":"bg-muted text-muted-foreground hover:text-foreground"}`}>{start}–{end}</button>})}<button onClick={()=>setFullMonth(true)} className={`hidden rounded-md px-2.5 py-1.5 text-xs font-medium md:block ${effectiveFullMonth?"bg-primary text-primary-foreground":"bg-muted text-muted-foreground"}`}>Full Month</button></div>{!effectiveFullMonth&&<div className="flex gap-1"><Button size="icon-sm" variant="outline" aria-label="Previous week" disabled={rangeStart===1} onClick={()=>setRangeStart(Math.max(1,rangeStart-7))}><ChevronLeft/></Button><Button size="icon-sm" variant="outline" aria-label="Next week" disabled={rangeStart+7>daysInMonth} onClick={()=>setRangeStart(rangeStart+7)}><ChevronRight/></Button></div>}</div>
    </CardContent></Card>
    <Card className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-4 py-3"><div className="flex flex-wrap gap-2">{legend.map(([code,label])=><span key={code} className="flex items-center gap-1 text-[11px] text-muted-foreground"><b className={`inline-flex min-w-7 justify-center rounded border px-1.5 py-1 ${statusStyle[code]}`}>{code}</b>{label}</span>)}</div><p className="text-xs text-muted-foreground">Scroll horizontally to view all dates.</p></div>
      {effectiveFullMonth&&<div ref={topScroll} onScroll={()=>sync("top")} className="overflow-x-auto overflow-y-hidden border-b" aria-label="Top horizontal scrollbar"><div style={{width:`${220+daysInMonth*54+512}px`,height:12}}/></div>}
      <div ref={tableScroll} onScroll={()=>sync("table")} className="max-h-[620px] overflow-auto scroll-smooth"><table className="min-w-max border-separate border-spacing-0 text-xs"><thead className="sticky top-0 z-30"><tr><th className="sticky left-0 z-50 w-[220px] min-w-[220px] border-b border-r bg-muted px-4 py-3 text-left shadow-[4px_0_8px_-6px_rgba(0,0,0,.5)]">Employee</th>{visibleDays.map(day=>{const date=new Date(`${selectedMonth}-${String(day).padStart(2,"0")}T00:00:00`);const weekend=[0,6].includes(date.getDay());const holiday=rows.some(row=>row.days[day-1]?.code==="H");return <th key={day} className={`w-[54px] min-w-[54px] border-b border-r px-1 py-2 text-center font-medium ${holiday?"bg-cyan-50":weekend?"bg-slate-100":"bg-muted"} ${day===todayDay?"relative text-primary after:absolute after:inset-0 after:border-2 after:border-primary after:content-['']":""}`}><span className="block text-sm font-semibold">{day}</span><span className="text-[10px] text-muted-foreground">{date.toLocaleDateString("en-US",{weekday:"short"})}</span></th>})}<SummaryHeaders/></tr></thead><tbody>{filtered.map(row=><tr key={row.employeeId} className="group"><td className="sticky left-0 z-20 w-[220px] border-b border-r bg-card px-4 py-2.5 shadow-[4px_0_8px_-6px_rgba(0,0,0,.5)] group-hover:bg-muted/30"><button className="text-left" onClick={()=>setSelectedEmployee(row)}><span className="block font-semibold hover:text-primary hover:underline">{row.name}</span><span className="text-[10px] text-muted-foreground">{row.employeeCode} · {row.department}</span></button></td>{visibleDays.map(day=>{const detail=row.days[day-1];const date=new Date(`${selectedMonth}-${String(day).padStart(2,"0")}T00:00:00`);const weekend=[0,6].includes(date.getDay());return <td key={day} className={`border-b border-r p-1 text-center ${detail?.code==="H"?"bg-cyan-50/60":weekend?"bg-slate-50":day===todayDay?"ring-2 ring-inset ring-primary":""}`}><Tooltip><TooltipTrigger render={<button className={`inline-flex h-7 min-w-8 items-center justify-center rounded border px-1 text-[10px] font-bold transition hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${statusStyle[detail?.code??"—"]}`}/>} aria-label={`${row.name}, ${detail?.date}, ${detail?.status}`}>{detail?.code??"—"}</TooltipTrigger><TooltipContent side="bottom" className="block w-72 max-w-72 bg-popover p-3 text-popover-foreground shadow-xl ring-1 ring-border"><p className="font-semibold">{row.name}</p><p className="mb-2 text-muted-foreground">{new Date(`${detail.date}T00:00:00`).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})} · {row.shiftTiming}</p><DetailGrid detail={detail}/></TooltipContent></Tooltip></td>})}<SummaryCells row={row}/></tr>)}{filtered.length===0&&<tr><td colSpan={visibleDays.length+7} className="py-16 text-center text-muted-foreground">No employees match the selected filters.</td></tr>}</tbody></table></div>
    </Card>
    <EmployeeDrawer employee={selectedEmployee} open={Boolean(selectedEmployee)} onOpenChange={open=>{if(!open)setSelectedEmployee(null)}}/>
  </div></TooltipProvider>;
}

function FilterSelect({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}) { return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className="h-9 rounded-lg border bg-background px-3 text-sm"><option value="">{label}</option>{options.map(option=><option key={option}>{option}</option>)}</select>; }
function SummaryHeaders(){return <>{[["Present",72],["Absent",72],["Leave",68],["WFH",68],["Late Days",78],["Effective Hours",112]].map(([label,width],index)=><th key={String(label)} style={{right:[398,326,258,190,112,0][index],width:Number(width),minWidth:Number(width)}} className="sticky z-50 border-b border-l bg-muted px-2 py-3 text-center shadow-[-4px_0_8px_-7px_rgba(0,0,0,.5)]">{label}</th>)}</>}
function SummaryCells({row}:{row:AttendanceMatrixRow}){return <>{[row.present,row.absent,row.leave,row.wfh,row.late,hours(row.effectiveMinutes)].map((value,index)=><td key={index} style={{right:[398,326,258,190,112,0][index],width:[72,72,68,68,78,112][index],minWidth:[72,72,68,68,78,112][index]}} className="sticky z-20 border-b border-l bg-card px-2 py-3 text-center font-semibold shadow-[-4px_0_8px_-7px_rgba(0,0,0,.45)] group-hover:bg-muted/30">{value}</td>)}</>}
function DetailGrid({detail}:{detail:AttendanceDayDetail}){return <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-[11px]">{[["Check-in",detail.checkIn],["Check-out",detail.checkOut],["Late by",`${detail.lateMinutes} min`],["Gross hours",hours(detail.grossMinutes)],["Break",hours(detail.breakMinutes)],["Effective",hours(detail.effectiveMinutes)],["Status",detail.status],["Regularization",detail.regularization]].map(([label,value])=><div key={label} className="contents"><span className="text-muted-foreground">{label}</span><b className="text-right">{value}</b></div>)}</div>}
function EmployeeDrawer({employee,open,onOpenChange}:{employee:AttendanceMatrixRow|null;open:boolean;onOpenChange:(open:boolean)=>void}){return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="w-full overflow-y-auto sm:max-w-xl"><SheetHeader className="border-b p-6"><SheetTitle>{employee?.name}</SheetTitle><SheetDescription>{employee?.employeeCode} · {employee?.department} · {employee?.shift}</SheetDescription></SheetHeader>{employee&&<div className="space-y-6 p-6"><div><h3 className="mb-3 font-semibold">Monthly attendance summary</h3><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Working days",employee.days.filter(day=>!["—","WO","H"].includes(day.code)).length],["Present",employee.present],["Absent",employee.absent],["Leave",employee.leave],["WFH",employee.wfh],["Late",employee.late],["Gross hours",hours(employee.grossMinutes)],["Effective hours",hours(employee.effectiveMinutes)],["Overtime",hours(employee.overtimeMinutes)],["Pending requests",employee.pendingRegularizations]].map(([label,value])=><div key={label} className="rounded-xl border bg-muted/30 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div></div><div><h3 className="mb-3 font-semibold">Daily attendance timeline</h3><div className="space-y-2">{employee.days.filter(day=>day.code!=="—").map(day=><div key={day.date} className="flex items-center gap-3 rounded-lg border p-3"><Badge className={statusStyle[day.code]}>{day.code}</Badge><div className="min-w-0 flex-1"><p className="font-medium">{new Date(`${day.date}T00:00:00`).toLocaleDateString("en-IN",{weekday:"short",day:"numeric",month:"short"})}</p><p className="text-xs text-muted-foreground">{day.checkIn} – {day.checkOut} · Effective {hours(day.effectiveMinutes)}</p></div>{day.lateMinutes>0&&<span className="text-xs font-medium text-orange-600">Late {day.lateMinutes}m</span>}</div>)}</div></div></div>}</SheetContent></Sheet>}
